### ISSUE TITLE
Force column with grouping widgets

### ISSUE THREAD

**Issue by terwarf** [Mottie/tablesorter#1000]
Hello Mottie,

is there any way to force the grouping widget to only group on a specified column, regardless from the sorting of the table?
I'm using multiple hidden rows to build groups with forced sorting order - but the first column in the sorting list isn't the one I want to create the groups from (which workes fine).

My wish would be a new option for the widget, something like 'group_forceGrouping = [3, 1]'

**Comment by Mottie** [comment]
Hi @terwarf!

Right now the grouping widget can only group one column at a time. A good portion of it would need to be rewritten to deal with multiple columns. Other than that, it wouldn't be difficult to make the group widget force group one column.

**Comment by terwarf** [comment]
Hi @Mottie,

thanks for the fast response - forcing to group one single column would be perfectly fine for me.

**Comment by Mottie** [comment]
I was just messing with the code... the way it is set right now would group the rows without even requiring a sort. Is that okay or should I include a check to make sure a sort is applied to the table? Hmm, maybe I should add an option for that too LOL.

**Comment by terwarf** [comment]
Well - we love options - don't we? ;)

**Comment by Mottie** [comment]
Ok, done. The update is available in the master branch.

The new options are:

* `group_forceColumn` (default `[]`) - Apply the grouping widget only to selected column; only the first value of the array is used; set as an array for future expansion.
* `group_enforceSort` (default `true`) - Only apply group_forceColumn when a sort is applied to the table.

It took me a bit longer than I planned because the method used to save collapsed groups wasn't working after adding these new options; but everything should be good now.

Someday when I have more time, I'll make the grouping widget work with multiple columns.

**Comment by terwarf** [comment]
Hi @Mottie,

works like a charme for me.
Didn't testet the group_enforceSort - option, as my tables have a forced sort order anyway.

Thank's a lot for your great work and the impressing fast reactions.

**Comment by Mottie** [comment]
Version 2.23.3 is now available with these changes.
