### ISSUE TITLE
Table Pagination not showing {startRow} to {endRow} ,until number of rows to be displayed are shown.

### ISSUE THREAD

**Issue by patilprajaktab** [Mottie/tablesorter#1009]
I am using table Pagination of table sorter, but untill I do not select number of rows to be displayed the startrow to endrow is not displayed in input class.

**Comment by Mottie** [comment]
Hi @patilprajaktab!

Can you provide a demo of the problem? 

Modify one of these: pager [addon](http://jsfiddle.net/1a5yu8yq/) / [widget](http://jsfiddle.net/yfwwzvL8/)

Because I am not seeing the problem in either the [pager addon](http://mottie.github.io/tablesorter/docs/example-pager.html) or [pager widget](http://mottie.github.io/tablesorter/docs/example-widget-pager.html) demos.

**Comment by Mottie** [comment]
Oh wait, you said input class?!

If you copied the pager HTML from the original tablesorter, it is a little different in this fork. Instead of displaying the start and end row inside an input, it adds it to any element with a `"pagedisplay" class name:

```html
<div class="pager">
	<img src="../addons/pager/icons/first.png" class="first" alt="First" />
	<img src="../addons/pager/icons/prev.png" class="prev" alt="Prev" />
	<span class="pagedisplay"></span> <!-- this can be any element, including an input -->
	<img src="../addons/pager/icons/next.png" class="next" alt="Next" />
	<img src="../addons/pager/icons/last.png" class="last" alt="Last" />
	<select class="pagesize" title="Select page size">
		<option value="10">10</option>
		<option value="20">20</option>
		<option value="30">30</option>
		<option value="40">40</option>
	</select>
	<select class="gotoPage" title="Select page number"></select>
</div>
```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
