### ISSUE TITLE
Month problem

### ISSUE THREAD

**Issue by fcferreira29** [Mottie/tablesorter#1016]
i am having a problem with the month,

is there a way to change the array of months? 
because it starts with 0,1,2,3,4.....
but we need it to be 1,2,3,4,5 (because we are using natural numbers, without the zero)

**Comment by Mottie** [comment]
Hi @fcferreira29!

Please provide the code being used.

**Comment by fcferreira29** [comment]
is there a way to change this array?

group_months      : [ "Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez" ],

when we output the array it starts with a 0 and we want it to start as 1,2,3,4....

**Comment by Mottie** [comment]
The group widget is set up to use zero-based indexing on that setting, so it should work correctly. In javascript when you use [`.getMonth()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth), it returns a zero-based index value, so that is why it is set up that way.

If you share the code you are using, I could help; but the basic solution is to take whatever month one-based index you have and subtract one. Something like this:

```js
var user_selected_month = 12,
  months = [ "Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez" ];

alert( months[ user_selected_month - 1 ] );
```
