### ISSUE TITLE
activate or disable group widget

### ISSUE THREAD

**Issue by fcferreira29** [Mottie/tablesorter#1017]
is there a way to activate the group only for a restricted group of tables?

i have implemented the group widget, and inserted the options on the tablesort main file, 

the problem is that the group is applied on all tables, and i want to choose witch has or has not the group effect,

Thanks

**Comment by Mottie** [comment]
Hi @fcferreira29!

Please provide the code being used.

If I had to guess at a solution for you, I would tell you to try adding "widget-group" to the table class name instead of defining it in the `widgets` option. The class name description and template can be modified using the [`widgetClass` option](http://mottie.github.io/tablesorter/docs/#widgetclass).

**Comment by Mottie** [comment]
The next time you have a bunch of questions, please try one of the [methods to get support](https://github.com/Mottie/tablesorter#questions). I would prefer to keep this "issues" section limited to problems with the code, or to enhancement requests. Thanks!

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
