### ISSUE TITLE
Tablesorter avoiding wild searches

### ISSUE THREAD

**Issue by raviankam525** [Mottie/tablesorter#1041]
We are using jQuery tablesorter to filter the data table in our application. I want to filter across multiple columns so I am unsing the below code,

```js
var filter_defaultFilterValue = {};
filter_defaultFilterValue[$('#policyListTable').find('th').length] = '{q} AND {q}';
```

and in widgetoptions

```js
filter_defaultFilter: filter_defaultFilterValue,
```

This works fine for me, but I am not able to avoid wild search(*,|,$) even if I use

```js
delete $.tablesorter.filter.types.wild;
```

Any help on avoiding a particular type of filter in these type of scenario?

**Comment by Mottie** [comment]
Hi @raviankam525!

From looking at that code, it appears that the "any" match filter is being set.

You can combine filter types if you only want exact AND matches: `'{q}" AND {q}"`

[Here is a demo](http://jsfiddle.net/856bzzeL/674/)

Please note that you will not be able to match cells that contain any spaces... trying to find "Aaron Johnson Sr Esq" will not return any results because the default filter breaks up the query at every space. So the filter widget would be looking for "Aaron AND Johnson AND Sr AND Esq" exact matches. Internally, it creates a regex for each query that becomes `/^(Aaron)$/i`, `/^(Johnson)$/i`, `/^(Sr)$/i` and `/^(Esq)$/i`.

If you want to change the way the query is being split, you'll need to change the regular expression after the filter widget initializes:

```js
$('table').tablesorter({
  // other options
  initialized: function( table ) {
    // this is the default regex, it is created upon initialization and is dependent
    // on the $.tablesorter.language.and setting (default is "and")
    $.tablesorter.filter.regex.andSplit = /(?:\s+(?:and|&&)\s+)/gi
  }
});

**Comment by raviankam525** [comment]
Thank you!
My actual question is how I can avoid/remove wild(*,?,|), fuzzy(~) and or(|) searches.
So for ex, if I enter *, I should get only row which contain * in them. And I still want to be able to do AND search. so for ex: if in a same row, if a column contains "*Bob" and another column contains "123" and if I search with "* 123", then I should be able to get that row.
So to remove wild card searches, I tried "delete $.tablesorter.filter.types.wild;", but it didn't work with my default filter.
Please help.

**Comment by Mottie** [comment]
Hmm, try the following code then:

```js
$('table').tablesorter({
  // other options
  initialized: function( table ) {
    $.tablesorter.filter.regex.wild01 = null;
    $.tablesorter.filter.regex.wild0More = null;
    delete $.tablesorter.filter.types.wild;
  }
});
```

Sorry, I didn't get a chance to test it...

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
