### ISSUE TITLE
Only want to fix collumns (with different rowspans) and fixed header

### ISSUE THREAD

**Issue by pedropcruz** [Mottie/tablesorter#1079]
Hello,

The first thing i need to say it's: good plugin!

The second one, i have this table like this: http://prntscr.com/915ear and only want to show on mobile, and the only 3 fixedcollumns, no sorter or search in there, just the fixed collumn and header

I try many things, and have no conclusion. Can you explain to me how i do this?

Thanks

**Comment by Mottie** [comment]
Hi @pedropcruz!

The setup you mention doesn't require tablesorter. You'll need to add four tables and have them set up with the same column width and row height.

**Comment by pedropcruz** [comment]
Humm... Can you help me with that?
I will show to you my problem with jsfiddle... Only to understand how to do that...
http://jsfiddle.net/pedropcruz/a59cg81q/
In my fiddle doesnt work stickyheader lol, but on my project is perfect.
And what i need its to fix the first 3 collumns. Can you help me with that @Mottie ?
Thank you!

**Comment by Mottie** [comment]
Making that table work without tablesorter would take a while, and it would just be easier to use tablesorter.

Anyway, try this: http://jsfiddle.net/Mottie/a59cg81q/2/

I added a `"sorter-false"` class to every header cell, and added a [`delayInit` option](http://mottie.github.io/tablesorter/docs/#delayinit) to not bother parsing all the data in the table.

**Comment by pedropcruz** [comment]
Yeah, i had that conclusion too, but without delayInit option :)
But we had a problem, when you fix the columns, he catches in every row, 3 td or th, as you can see on the print: http://prntscr.com/91v3lj
I dont solved this problem already, but i added 3 classes, and i want only he fixes the td's have the 3 classes that i added.
It's possible to do that?
Many thanks

**Comment by Mottie** [comment]
Sorry for not responding earlier. The scroller widget isn't "smart" enough to break colspans that span a frozen column. So if you want a smooth break in a frozen column, split the colspan at the break.

Honestly, I haven't touched the scroller widget in a while. I'm really not happy with it overall as a widget since it is so inefficient and finnicky. Eventually I would like to rewrite it along with the core plugin to target a container for each column to make sticky columns and column reordering work much better. But sadly I lack that time and energy right now.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
