### ISSUE TITLE
Print table headers on all pages

### ISSUE THREAD

**Issue by clod986** [Mottie/tablesorter#1097]
Hi @Mottie ,
I was wondering if there's a way to print the thead on all pages for long tables.

Thanks!

**Comment by Mottie** [comment]
Hi @clod986!

This is actually an issue with webkit browsers (ref [1](https://code.google.com/p/chromium/issues/detail?id=24826) &amp; [2](https://bugs.webkit.org/show_bug.cgi?id=17205)).

However, Firefox does print table headers and footers on every print page. Sadly, Firefox doesn't have a built-in print preview - you can add one like [print/print preview](https://addons.mozilla.org/en-US/firefox/addon/printprint-preview/) but even that won't work in the popup window.

It's not something tablesorter can fix... it *might be possible* but highly unlikely to work around. A fix would entail getting the set page size (e.g. A4, A5, B5, Legal, Letter, etc), print font size, paper orientation, page height (which might change if the user scales the page (e.g. "shrink to fit"). And then finally breaking the table into appropriately size blocks so that a header and/or footer can be included.

So yeah, not going to happen.
