### ISSUE TITLE
Problem with tablesorter

### ISSUE THREAD

**Issue by fcferreira29** [Mottie/tablesorter#1104]
Hello,

i am having a little problem with the tablesorter,

here is the problem,

i have a table with 170 lines, and the limit on each page is 100 lines,

when i change to the next page, the number of lines is 70, 

the problem is that when i change to the next page, the page does not scroll up (and since the limit is 100 the 70 remaining lines get sort of hidden since the scroll does not go up), 

i would sugest this as an improvment, 

Thanks,

Fábio Ferreira

**Comment by Mottie** [comment]
Hi Fábio!

You can bind to the "pagerChange" event and scroll the window to the top ([demo](http://jsfiddle.net/Mottie/1a5yu8yq/99/)):

In that demo, shrink the result window down and set the page size to 30 - it may not do this if you've been to jsFiddle before since the page size is being saved to local storage. Then scroll to the bottom and change pages.. the `.scrollTop` function will move you to the top of the page

```js
$(function () {
	$('table').on('pagerChange', function(){
  	$(window).scrollTop(0);
  }).tablesorter({
		theme: 'blue',
	}).tablesorterPager({
		container: $('.pager'),
    size: 30
	});
});
```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
