### ISSUE TITLE
Issue with filter widget and UI range / slider

### ISSUE THREAD

**Issue by fab-girard** [Mottie/tablesorter#1107]
Hello,
I've tried to upgrade tablesorter from 1.16.5 to 1.19.3 (and now 1.20.0) and a problem occurs with a filter function using a jquery UI slider. Here the jsfiddle:
http://jsfiddle.net/f58479re/1/

Try to use slide, an error will occurs : n.split is not a function
Before, I got "05:00,08:00" in `n` parameter from `filter_functions`. Now I get an Integer... 946699200000 Seems to have a problem with "parsed" fields.

Thanks for your support,
Fabien

**Comment by TheSin-** [comment]
the problem isn't with TS it's in your JS code

```
n = n.split(',');     n.split is not a function. (In 'n.split(',')', 'n.split' is undefined)
```

**Comment by TheSin-** [comment]
added more explanation and a working example.

**Comment by fab-girard** [comment]
Hello,
thanks I thought it was a regression since retourned values have changed. Strange not to get exact content of the cell like before...
Fab

**Comment by TheSin-** [comment]
I'm going to look deeper into it on the site there is a proposed change to the function params I wonder it that change has started early, I'll talk to @Mottie about it

**Comment by Mottie** [comment]
The reason you're seeing a change from v1.16.5 is because the time parser now extracts out the time in case you manually set the time parser on a full date column like "12/18/2015 6:30 PM" - it will now only target the "6:30 PM"

So, if you look at the [`filter_function`](http://mottie.github.io/tablesorter/docs/#widget-filter-functions) parameters:

```js
// function variables:
// e = exact text from cell
// n = normalized value returned by the column parser
// f = search filter input value
// i = column index
// $r = jQuery element of current row
// c = table.config
// data = combined filter data
0: function( e, n, f, i, $r ) { ... }
```

You will see that `n` is the normalized (or parsed) data, so if the time parser is being detected - I'm not sure why since the times in the example have two times with a comma separator - it will parse and save that time as the [number of milliseconds since the epoch](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime).

To get exact table cell content, use `e`.

I [updated your demo](http://jsfiddle.net/Mottie/f58479re/4/), and added a "sorter-text" class to the header cell.... but I'm not sure what the slider is supposed to do. I can slide it all the way across and it doesn't do anything. What were you wanting that range slider to do?

**Comment by Mottie** [comment]
Ok, I fixed the time detection regex.

**Comment by TheSin-** [comment]
It needs the filtered class added, and when I checked n and e where the same

**Comment by fab-girard** [comment]
Hello,
for info the `e` parameter didn't contain exact value but the same value than `n`... The 2 parameters contain a timestamp and none the exact text. It was the reason of my issue.

Here my scenario: the column contains hour time slot, for instance 08:00,12:00 and 10:00,14:00. By using the slider, I want to filter all lines which contain for instance 12:00,14:00 (12-14 with the slider). Maybe there is a better way to do it...

Regards,
Fabien

**Comment by Mottie** [comment]
That is odd, the `e` should contain the exact text. I will investigate further.

Alternatively, you can use the other parameters like this:

```js
0: function( e, n, f, index, $row ) {
  var txt = $row.children().eq(index).text();
  // process txt & return boolean
}
```

or if you are using the latest filter widget, a [`data` parameter](http://mottie.github.io/tablesorter/docs/example-widget-filter-custom-search.html#how_to_add_custom_filter_types) is also included:

```js
0: function( e, n, f, i, $r, c, data ) {
  var txt = data.$cells.eq(data.index).text();
  // process txt & return boolean
}
```

I tried updating your demo, but it isn't working... I think it's the comparison logic in the `return`. I'll attempt to figure it out when I get some time today.

**Comment by TheSin-** [comment]
I agree my tests showed the parser value for e and n.  Hence my comment that maybe the planned changes had already accidentally started, my computer was tied up all weekend so I didn't have a chance to check on it either.

and as you can see in my jsfiddle I kinda did the same as @Mottie, I just didn't use children(), cause @Mottie is better then me ;)
