### ISSUE TITLE
scroller use ie8 and scroll auto jumping?

### ISSUE THREAD

**Issue by GoGillDong** [Mottie/tablesorter#1112]
Hi Mottie,

scroller widgets use ie8,

table header click -> down scrolling -> auto up scroll !!

![tablesorter_scroller_ie8_bug](https://cloud.githubusercontent.com/assets/5512509/12044974/226dcb3a-aede-11e5-80ea-ab504389558a.png)

![honeycam 2015-12-30 09-24-46](https://cloud.githubusercontent.com/assets/5512509/12044981/275855f2-aede-11e5-8d63-7698f313e260.gif)

Thanks Mottie

**Comment by Mottie** [comment]
Hi @GoGillDong!

I don't have IE8 to test this issue on, but I think the problem might be the [`scroller_jumpToHeader` option](http://mottie.github.io/tablesorter/docs/example-widget-scroller.html#scroller-jump-to-header) which is `true` by default. Set it to `false` and see if that fixes the issue in IE8.

**Comment by GoGillDong** [comment]
Hi @Mottie 

IE8 to scroller jumping issue, scroller_jumpToHeader option was true->false ..

um.. um..

this issue not clear..

continue to try testing this issue

thank you!!

**Comment by Mottie** [comment]
Well, since [Microsoft no longer supports IE10 and lower](https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support), I don't think you need to worry about this issue any more.

I don't think there is a fix for this problem anyway, so I'm going to close this issue.

Please don't hesitate to continue our discussion in this thread if you so desire.
