### ISSUE TITLE
Output Widget: export table caption with output_includeCaption (like output_includeFooter)

### ISSUE THREAD

**Issue by tomaszn** [Mottie/tablesorter#1121]
Hi!
It would be great if an option like output_includeCaption existed for Output Widget. When exporting to CSV one could use it to prepend a title to the table data, so the CSV file would be ready to print after opening in Excel.

**Comment by Mottie** [comment]
Hi @tomaszn!

From looking at the CSV specification ([RFC 4180](https://tools.ietf.org/html/rfc4180)), I don't see any standard defined for adding a caption or title to CSV data.

I just pushed an update to the output widget which allows you to use the [`output_callback` function](http://mottie.github.io/tablesorter/docs/example-widget-output.html#output_callback) to return a modified string instead of just a boolean. Use it like this ([demo](http://jsfiddle.net/Mottie/abkNM/7487/)):

```js
output_callback :  function(config, data)  {
	return config.$table.children('caption').text() + '\n' + data;
}
```

With this change you can do whatever you want to the data.

**Comment by tomaszn** [comment]
Thanks a lot! And usually we need to trim spaces from the text: ...text().**trim()** +...
