### ISSUE TITLE
filter focus problem

### ISSUE THREAD

**Issue by airthomas** [Mottie/tablesorter#1139]
Hi,

I have added "$('#tableso').find('.tablesorter-filter').eq(2).focus();" in modal of http://jsfiddle.net/njt1nth5/14/, but looks the focus not work.

Many thanks.

**Comment by Mottie** [comment]
Hi @airthomas!

Well, there were a few issues in that demo ([updated demo](http://jsfiddle.net/Mottie/njt1nth5/15/)):

1. The scroller widget is being used, so you can't target the main table because the main table is only showing the `tbody`. The `thead` and filter row are in a separate table.
2. The focus function needs to be added to the "update" callback function.
3. The focus function needs to be added inside a `setTimeout`. If the time is set to 400ms or less, the focus is shifted.

```js
$('#tableso').trigger('update', [true, function() {
  $(window).resize();
  setTimeout(function() {
    $('#plage-modal').find('.tablesorter-filter').eq(2).focus();
  }, 600);
}]);
```

**Comment by airthomas** [comment]
Well noted and thanks. It is work.
