### ISSUE TITLE
Sorting not working when image is present in cell

### ISSUE THREAD

**Issue by h3llrais3r** [Mottie/tablesorter#1149]
I have a problem when sorting when using a custom textExtraction function for a cell where images are imbedded in the cell.

You can find the example here: http://jsfiddle.net/wd97qs34/

If I remove images from the cells in the first column, it works.
With images present, I can't get it to work.
I'm using a textExtraction fuction to only extract the text from the link, so the image should be ignored for the sorting.

Is this a bug or am I forgetting something in the config?
Any help would be appreciated.

**Comment by Mottie** [comment]
Hi @h3llrais3r!

Since there is an image in the first column, tablesorter is detecting it and setting the parser to extract data from an image attribute (see [imgAttr](http://mottie.github.io/tablesorter/docs/#imgattr)).

To override the auto-detection of the image parser, set a class name in the header:

```html
<th class="sorter-text">Show/Movie name</th>
```

Also remove the `textExtraction` method - [demo](http://jsfiddle.net/Mottie/wd97qs34/2/).

**Comment by h3llrais3r** [comment]
Hi @Mottie.
Thanks for your quick aswer.
Adding the class to the table header fixes indeed my problem. :smile: 
But after having a look at the imgAttr specs, I found out that I can also fix it by setting it in the headers option:
`headers: {
                0: {sorter: "text"}
            }`
I prefer this way so I don't have too many styling in the html.
Thanks again and you've done a great work with this plugin. :+1:
