### ISSUE TITLE
Defer re-filter after updateRows

### ISSUE THREAD

**Issue by busturdust** [Mottie/tablesorter#1150]
Hello,

I have an external filter that calls the following function.

```
function hideRows() {
    var $table = $('.tablesorter'),
    filters = $.tablesorter.getFilters( $table );
    filters[2] = selected === 'All' ? '' : selected;
    $.tablesorter.setFilters( $table, filters );
}
```

Later, I update the value that this function is filtering on using a simple `.text()` call ( as well as other rows and cells throughout the table)

`workgroup_selector.text(tempValues.workgroup)`

After the loop has completed, and all values are updated, I call
`
$('#connectionGrid').trigger('updateRows', [false]);`

However, if the user is currently filtered into say `WG01`   and the `workgroup` value changes, the table rows will simply dissapear. I was hoping the `resort` flag would trickle to the filter as well, but it does not appear so. 

I would like to defer the "refiltering" mechanism, and leave the table there, but have any future filters, use the new value. 

For instance.

I am filtered on WG01, Record is updated to WG02, the record remains on the screen, but if I filter by WG02 the record should be on that list, and nolonger on the WG01 list. 

Please let me know if this is possible or if more information is required.

Thanks for reading!

**Comment by Mottie** [comment]
Hi @busturdust!

A demo showing this problem would really help me see this issue - if you would, please modify [this demo]() with a basic example.

If I am understanding correctly, the filter isn't reapplying correctly after the update? I wonder if it might be related to searching through already filtered rows... try setting the [`filter_searchFiltered` option](http://mottie.github.io/tablesorter/docs/#widget-filter-searchfiltered) to `false`. This setting ensures that filter searches are always performed on all rows instead of already filtered rows.

If that doesn't work, please share a bit more of the code being used to update the table, like the code that calls `hideRows`.

**Comment by busturdust** [comment]
Hi @Mottie 

Thanks for the speedy reply.

The filter actually **is reapplying correctly**  .. But I would like to **halt it from reapplying**  in the event of received **ajax value update**  I will work on modifying a complete demo as soon as possible, but need to find time

**Comment by Mottie** [comment]
Hmm, instead of using "updateRows", use [`updateCache`](http://mottie.github.io/tablesorter/docs/#updatecache) instead... this method will not re-apply the widgets or resort, it *only* updates the cache... but it does accept a callback so you can resort or apply filters if you want.

**Comment by busturdust** [comment]
Wonderful! It is working as expected. I was previously using `updateAll` to get the desired functionality but it was rather slow for my use. This is much faster, and works ! 

Thanks Mr Mottie!

**Comment by busturdust** [comment]
Holy Mottie man! Thanks for the help, I originally deleted the question because I thought the request was too vague or not fleshed out enough, but this is a great boost for me in understanding nesting.

Thanks again Mottie, you really are fantastic!
