### ISSUE TITLE
Numeric values not sorted, cache corrupted??

### ISSUE THREAD

**Issue by duclad** [Mottie/tablesorter#1161]
Hi, 

I have a strange issue.
I have a table with large numbers inside a column(eg 1200100000000000004,1200100000000000012).
The table is generated by a template framework and the table sorter is initialized inside $(function () {}) which is declared in the body of the generated html.

For all the columns the sorting is working fine( I have text, date columns) only for this one it does not sort.
Looking with the debugger I noticed this when building the cache

```
(index)    ID                                      PASSWORD
row: 0	1200100000000000000	"f8bd0dsdswwe0f0712ec2a74c05c25920439b7a"	
row: 1	1200100000000000000	"a5wewwewf8cd4b9a2ac357833b9b5a30ddcc70"	
row: 2	1200100000000000000	"5c68f55e4efc7fad322811ewewwb2e9ewa9e5e5"
```

From what it seems the column containing the ids has the wrong value inside, the last 2 digits are always replaced by a 0.

This is what I see after the parsing is done:

```
(index)parser extractor string empty
(0) ID "digit" "none" "none" "bottom"
(1) PASSWORD "text" "none" "none" "bottom"
```

Could you give me a hint about what is wrong?

This is how I intitalize the tablesorter:

```js
            $(function () {
                $('#table').tablesorter({
                    widthFixed:false,
                    debug: true,
                    usNumberFormat:false,
                    stringTo:'none',
                    headerTemplate: '{content}', // Add icon for various themes
                    widgets: ['zebra', 'stickyHeaders'],

                    widgetOptions: {
                        // jQuery selector or object to attach sticky header to
                        stickyHeaders_attachTo: $('#output') // or $('.wrapper')
                    }
                });

            });
```

Thanks,
Claudiu

**Comment by Mottie** [comment]
Hi Claudiu!

The problem is that the ID's are too large for javascript to parse from a string into a number - see [`Number.MAX_SAFE_INTEGER`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER).

So if you type in the following code into the console, you'll see the loss of precision in the results:

```js
Number.MAX_SAFE_INTEGER
// result = 9007199254740991 (16-digit number)

parseFloat('1200100000000000004'); // 19 digit number
// result 1200100000000000000 // still a 19-digit number, but precision is lost

// another example
parseFloat('1234567890123456789');
// result 1234567890123456800
```

So, I think the easiest solution is to add a new parser.

The parser doesn't do anything fancy, it just adds a comma every 12 digits (I just picked a nice round number that was less than 16 digits) and sets the parser type to "text". What that does change does is allows the alphanumeric sorting algorithm to "chunk" the value into smaller numbers that can be parsed and compared - [here is a demo](http://jsfiddle.net/856bzzeL/907/):

```js
$(function() {

  $.tablesorter.addParser({
    id: 'hugeNumbers',
    is: function() {
      return false;
    },
    format: function(str) {
      // add commas every 12 digits; Number.MAX_SAFE_INTEGER is 16 digits long
      // regex modified from: http://stackoverflow.com/a/2901298/145346
      return str.replace(/\B(?=(\d{12})+(?!\d))/g, ",");
    },
    type: 'text'
  });

  $('table').tablesorter({
    theme: 'blue'
  });

});
```

I'll also add this parser to the library so others can use it.

**Comment by Mottie** [comment]
Oh, I forgot to mention that to set the parser for the column, the easiest solutions would be to add a class name to the header cell:

```html
<th class="sorter-hugeNumbers">ID</th>
```

See the documentation on [this page](http://mottie.github.io/tablesorter/docs/example-parsers-class-name.html) for the other methods.

**Comment by duclad** [comment]
Thanks so much for your quick answer. It really saved my day. 
The solution works like a charm.
