### ISSUE TITLE
Updating table, sticky headers and maintaining the scrolling position.

### ISSUE THREAD

**Issue by Herst** [Mottie/tablesorter#1166]
To summarize a bit the discussions yesterday in the IRC between @TheSin- and me.

I have the following example of a table with changing content: http://jsfiddle.net/pcmsL943/28/
In all browsers I tested it with (Chrome, Fx, IE, Edge) I can scroll to a position and I will stay at this position even if the table updates (I don't care about the position when something is filtered BTW).

Now once I enable one of the stickyHeaders widgets the situation changes, suddenly the positions gets reset to the top-corner on every update, see: http://jsfiddle.net/pcmsL943/29/

A somewhat hacky workaround where I save the scrolling position to restore it later seems to work: http://jsfiddle.net/pcmsL943/30/, but this solution far from nice in part because it hinders scrolling while the update is running and the jump is visible in most browsers. Also according to @TheSin- this seems not to work in Safari.

@TheSin- advised me to clone the table header instead and pointed me to a proof of context of his: http://codepen.io/TheSin/pen/xkgKj. Maybe I am going try to implement this solution or I will simply ditch the sticky headers plugin altogether. Or maybe this thread here will lead to some other solutions, e.g. why would the "update" event even cause the whole document to be scrolled? Shouldn't the CSS3 sticky headers plugin not just be simply moving the table headers into a div with `position: sticky` set (with fallbacks for browsers not supporting it)?

**Comment by Mottie** [comment]
Hi @Herst!

Hmm, it appears the issue is actually a css3StickyHeaders widget option.

Set the [`cssStickyHeaders_filteredToTop`](http://mottie.github.io/tablesorter/docs/example-widget-sticky-header.html#stickyheaders-filteredtotop)<sup>&dagger;</sup> to `false` and everything should be okay - [demo](http://jsfiddle.net/pcmsL943/32/)

```js
$('#table1').tablesorter({
    //delayInit: true,
    // debug: true,
    theme: 'blue',
    widgets: ['zebra', 'filter', 'math', 'cssStickyHeaders'],
    widgetOptions: {
        filter_liveSearch: false,
        cssStickyHeaders_filteredToTop: false
    }
});
```

&dagger; *Note*: The link to that option points to the sticky headers widget demo and not the css sticky headers widget demo because the options are all the same, the only difference is the `css` in front.... and I'm too lazy to duplicate the options section in the other demo. :grin:

**Comment by Herst** [comment]
Oh my, how embarrassing that I missed that option. :sweat:

**Comment by Mottie** [comment]
Naw, it's easy to miss. And you're not the first one who has had an issue with it... maybe I should make it default to `false`.

**Comment by Mottie** [comment]
Has this been resolved? Can I close this issue?

**Comment by Herst** [comment]
Yes. Sorry, I thought you wanted to keep this open because of some of the tags.
