### ISSUE TITLE
Problem with sorting my elements

### ISSUE THREAD

**Issue by jmminy** [Mottie/tablesorter#1174]
Hi, 
I'm trying to use tablesorter for a table I created using a db query. 
The filter works fine but for some reason, it is impossible to use the sorting option. I did update my Jquery library but i have the same issue. 

Activating the debug, I see the table being modified in the console but nothing happen on the page. 
Other funny point: my settings seem to be recognized but not the sort; with no error log.

THanks in advance for your help.
I'm still searching..
Here is an embed using jsfiddle, hope it is enough:
`<script async src="//jsfiddle.net/jimbo75/wgm8jL0k/2/embed/"></script>`

**Comment by Mottie** [comment]
Hi @jmminy!

It looks like the issue is that every row outside the `thead` is wrapped in its own `tbody`

```html
<table>
  <thead>...</thead>
  <tbody><tr>Row 1</tr></tbody>
  <tbody><tr>Row 2</tr></tbody>
  ...
</table>
```

This fork of tablesorter will sort each group of `tbody` rows separately, but it won't sort rows across tbodies... well, unless you're using the [`sortTbodies` widget](http://mottie.github.io/tablesorter/docs/example-widget-sort-tbodies.html), but then things are a bit more complicated.

Anyway, I removed all the extra `tbody` definitions in [this demo](http://jsfiddle.net/Mottie/856bzzeL/917/). Also, I changed the use of class name meta data from this:

```html
<th class="{sorter : false, filter : false}">
```

to this:

```html
<th class="sorter-false filter-false">
```

Because using the meta-data method requires the [metadata plugin](https://github.com/Mottie/tablesorter/blob/master/js/extras/jquery.metadata.js) which isn't really used much any more and really only left as part of this plugin so you can switch from the original tablesorter to this fork with little to no changes.

**Comment by jmminy** [comment]
Hi Mottie !
Thanks a lot, it did the trick. My mistake...
I'll handle the pager now hopefully without any issue.
Thanks for your support.
