### ISSUE TITLE
load data only using ajax

### ISSUE THREAD

**Issue by southmeadows** [Mottie/tablesorter#1187]
I have been trying to read between all the posts on how to load data via ajax and json. I wasnt able to find a simple demo of this.  

Currently I load using PHP when the page refreshes. 

I have the ajax php setup already and it returns the field and data. 

Lost, hope someone has a demo of this on fiddle or something like that. 

thank you!

**Comment by Mottie** [comment]
Hi @southmeadows!

If you are using the pager widget/addon, it has ajax functionality baked in. You can check out the [main demo here](http://mottie.github.io/tablesorter/docs/example-widget-pager-ajax.html). Likely the main option you'll need to focus on is the [`ajaxProcessing` callback](http://mottie.github.io/tablesorter/docs/#pager-ajaxprocessing). That documentation link contains a bunch of examples on how to process the data returned from the ajax call. Also, there is [this jsFiddle](http://jsfiddle.net/Mottie/uwZc2/) which accesses random data provided by filltext.com - and because the data is random, sorting and filtering don't work - but it does provide another example of how to process data.

If you're only using ajax initially to populate the table. You can use jQuery to [`load()`](http://api.jquery.com/load/) HTML directly, or use [`$.ajax`](http://api.jquery.com/jQuery.ajax/) (sorry I don't have an example of these methods handy.... Or use the [build table widget](http://mottie.github.io/tablesorter/docs/example-widget-build-table.html) to do the work for you.

**Comment by southmeadows** [comment]
thanks for the info. I will just write one in javascript. 

-- 
Mark

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
