### ISSUE TITLE
2 jQuery UI Datepicker Comparison problem

### ISSUE THREAD

**Issue by emileletueur** [Mottie/tablesorter#1191]
Hi,

I use jQuery UI Datepicker Comparison on two seperate column, one with more or equal and other with less or equal.
I use so this two line for init my jquery date picker on filter_formatter :

            4: function ($cell, indx) { return $.tablesorter.filterFormatter.uiDateCompare($cell, indx, {compare: '>=', changeMonth: true, changeYear: true, dateFormat: "dd/mm/yy" }) },
            5: function ($cell, indx) { return $.tablesorter.filterFormatter.uiDateCompare($cell, indx, { compare: '<=', changeMonth: true, changeYear: true, dateFormat: "dd/mm/yy" }) },

I have one row on my tab dated for the current day and if i fix one filter with current day date for a least of column he hide this row.
If i delete one jQuery UI Datepicker Comparison by commenting, filter work as intended.

On idea about this problem ?

Chuz

**Comment by Mottie** [comment]
Hi @emileletueur!

Would you please provide an example.

Within the `uiDateCompare` code, I made it so that a `<=` comparison sets the time of day to 11:59:59 PM to include all times within that day. So also please check this by setting the `debug` option to `true` and looking in the console log at what filters are being used.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
