### ISSUE TITLE
Support multiple child rows per parent

### ISSUE THREAD

**Issue by jsight** [Mottie/tablesorter#1195]
If I have multiple css-childRow rows then the table gets completely trashed upon sorting. Can this be supported?

**Comment by Mottie** [comment]
Hi @jsight!

Sorry for the delay in response.

The code does support multiple child rows. Make sure that when the child rows are toggled the cells are restored properly.

* In [this demo](http://mottie.github.io/tablesorter/docs/example-child-rows.html), the parent row uses a `rowspan` to connect the child rows. When toggled, the child row cells (`td`) are hidden/shown instead of the row (`tr`).
* In [this demo](http://jsfiddle.net/abkNM/7992/), the child rows (`tr`) are completely hidden. When toggled, the associated children are hidden/shown.

If you need help, please modify the demo and I will help.

**Comment by jsight** [comment]
@Mottie - Thank you for the feedback. The second demo prompted me to investigate my issues further. It turns out that I was failing to call "update" after adding additional child rows. This was causing the sort itself to behave very strangely with the multiple child rows.

Calling update (as apparently I should have been all along) fixes the issue.

Thanks for your help!
