### ISSUE TITLE
Multisort by default, without holding the sortMultiSortKey

### ISSUE THREAD

**Issue by hmundt** [Mottie/tablesorter#1200]
It would be nice to be able to use MultiSort by default instead of having to hold down the key specified in sortMultiSortKey. Is this possible with the current version or planned for the future?

**Comment by Mottie** [comment]
Hi @hmundt!

It isn't documented (yet), but since the [`sortMultiSortKey` option]() can be set to any [event object](http://docs-beta.stackexchange.com/documentation/javascript/287/events/1247/event-object#t=201604261156130846621), you can pick one that is pretty much always "truthy" ([demo](http://jsfiddle.net/Mottie/856bzzeL/1018/)):

```js
$(function () {
  $('table').tablesorter({
    theme: 'blue',
    // event.bubbles "should" always be truthy here
    sortMultiSortKey: "bubbles",
    // Use Ctrl + click to remove a column from sorting.
    sortResetKey: 'ctrlKey',
    widgets: ['zebra', 'columns']
  });
});
```

**Comment by hmundt** [comment]
This is perfectly sufficient for me.
Thank you for the support and for the continued development of this wonderful library.

**Comment by Mottie** [comment]
I'm glad that worked for you! <img title=":_ happy :" src="https://cloud.githubusercontent.com/assets/136959/13559407/7996bb94-e3d9-11e5-9b36-a39832cd3ceb.gif">
