### ISSUE TITLE
Tablesorter Column Selector Widget with multiple columns having the same priority

### ISSUE THREAD

**Issue by max5555** [Mottie/tablesorter#1204]
The table do not scale in horizontal direction properly. The columns appear when there is not enough space for them. See the screenshot: https://yadi.sk/i/YEZMIwfvrNLNq and corresponding example: http://jsfiddle.net/max5555/0jt400Lg/ The problem is that the number of priorities is limited, so the same priority has to be assigned to multiple columns, but in this case it is hard to fit table width due to the problem mentioned above.

**Comment by Mottie** [comment]
Hi @max5555!

The issue, I think, is that tables stop resizing once they can't wrap the longest word in the content. So if you add the following CSS the text can wrap and keep the table from overflowing ([demo](https://jsfiddle.net/Mottie/mcn8o3yu/7/)):

```css
td, th {
  white-space: pre-wrap;
  word-break: break-all;
}
```

I think you should be able to use `text-overflow: ellipsis`, but I think it requires you to set a max width on the table column - [here is an example](http://jsbin.com/soqufiguca/1/edit?html,output), but it isn't exactly the same issue as this one - I've tried different methods to get the ellipsis to work without setting a width but I haven't been successful.

**Comment by max5555** [comment]
Can you explain why the the number of priorities is limited to 6? How can I increase this number?

**Comment by Mottie** [comment]
The reason only 6 priorities are defined is because I wanted to keep the settings similar to jQuery Mobile's table widget. This widget combines both the [table column toggle](http://demos.jquerymobile.com/1.4.5/table-column-toggle/) and [table reflow](http://demos.jquerymobile.com/1.4.5/table-reflow/) functions.

Personally, I think 15 priorities is too many. The reason there are only a few is because it's more work defining a layout for each priority (screen width). And there really aren't that many [differences in screen widths](https://design.google.com/devices/) that need to be addressed. So if the table has 15 priorities, what about the rest of the page?

That being said, you are more than welcome to do whatever you want. I have no issues with adding a new option that lets you set the number of priorities. That way you won't need to go in and edit the widget after each update.

**Comment by max5555** [comment]
Now I came to just perfect solution. I generate the table with a python script, and I just add the code calculating minimum width required for each column to generate `columnSelector_breakpoints` automatically to get something like  `[ '45em', '51em', '57em', '61em', '65em', '68em', '71em', '75em', '79em', '82em', '92em', '99em', '106em' ]`. Using this approach I have just perfect result: the table is perfectly scaled in horizontal direction (I will add a link to the final result a bit later). 

Now I understand that I can do the same using 6 priorities, but columns will appear by two-three or more at the same time, and the scaling is not "smooth" in this case. It would be nice to add an option for maximum number of priorities. I tried to replace 6 by an option `wo.columnSelector_maxpriorities` but with no luck up to now.

**Comment by Mottie** [comment]
You know with a base 16 px font size, that the difference between 65em and 68em is only 48 pixels?

So the breakpoints  being set are:

##### Base 16px font size

| em |  px |
|----:|-----:|
| 45em | 720px |
| 51em | 816px |
| 57em | 912px |
| 61em | 976px |
| 65em | 1040px |
| 68em | 1088px |
| 71em | 1136px |
| 75em | 1200px |
| 79em | 1264px |
| 82em | 1312px |
| 92em | 1472px |
| 99em | 1584px |
| 106em| 1696px |

**Comment by Mottie** [comment]
New version released. A `columnSelector_maxPriorities` option is now available.

**Comment by max5555** [comment]
> You know with a base 16 px font size, that the difference between 65em and 68em is only 48 pixels?

I know that. One of the columns has the header word with two letters, so the width in 3em is just perfect isn't it?

Many displays has HD resolution, e.g. my desktop monitor has resolution 1920x1080, so I see no problem about 106em=1696px.
