### ISSUE TITLE
jquery.tablesorter.js:1 Uncaught TypeError: a.replace is not a function

### ISSUE THREAD

**Issue by CaineInc** [Mottie/tablesorter#1213]
I have a table that contains 12-13 pcs sortable columns but I'm getting this error when some columns are being clicked to sort the related rows. The columns that give this error have float numbers and empty rows. I think the reason of this error may be associated with them. But, i haven't figured it out yet. :/

![error](https://cloud.githubusercontent.com/assets/5685613/15180718/f124272e-178b-11e6-8142-0dfdc98809e4.png)

**Comment by Mottie** [comment]
Hi @CaineInc!

The natural sort function is always expecting string values, since it shouldn't encounter them if the parser is set as "text". I didn't do this because any extra operations within the sort function would only slow the process down. It may only be a minimal slowing, but that sometimes makes a big difference in IE.

Anyway, If you are using a custom parser, make sure the type is set as "numeric":

```js
$.tablesorter.addParser({
  id: 'number',
  is: function(s, table, cell, $cell) {
    // return false so this parser is not auto detected
    return false;
  },
  format: function(s, table, cell, cellIndex) {
    return parseFloat(s);
  },
  // set type, either numeric or text
  type: 'numeric'
});
```

Or, make sure to set the column parser as a digit:

```html
<th class="sorter-digit">Values</th>
```

**Comment by CaineInc** [comment]
Hi @Mottie,

Thanks for your comment. But, sadly i'm still getting same error even though i try the both ways

I'm using tablesorter 2.0 with jquery-ajax and to clarify this error for you i would like to share some piece of my project sources.

![1](https://cloud.githubusercontent.com/assets/5685613/15182365/b978713c-1794-11e6-939b-a33fbbedcf21.png)

![2](https://cloud.githubusercontent.com/assets/5685613/15182396/e6f67eec-1794-11e6-9e09-58801a4cef14.png)

![3](https://cloud.githubusercontent.com/assets/5685613/15182433/142b6cba-1795-11e6-9adc-52f87c7fddc5.png)

Thanks in advance for your help

**Comment by Mottie** [comment]
The "number" parser I shared above was really just an example... it doesn't handle empty strings, remove commas spaces and other non-digit characters, nor does it return the string if the result is not a numeric value. The built-in "digit" parser should do all that automatically.

Anyway, it would help if you could share some example values from the column causing problems.

Lastly, the `change` callback in the ajax success function should be moved outside of that function and use delegated binding instead of binding directly to the checkbox. Something like this:

```js
$("table tbody").on("change", ":checkbox", function(){
    $(this).closest('tr').toggleClass('selected', this.checked);
    addItems($(this).val(), this.checked);
});

$.ajax(
{
    // ...
    success: function(feedback)
    {
        // remove $('tbody :checkbox').change code from here
    }
});
```

**Comment by CaineInc** [comment]
I solved this problem by changing **update** command to **updateAll** command in jquery trigger function as below. 

`$('#datazone').html(feedback).trigger('updateAll');`

After this change, the custom parser codes you shared worked.

Thanks for your help.

**Comment by Mottie** [comment]
I wouldn't recommend using "updateAll" since it is intended to be used when the `thead` content changes. Unless that is actually what you are doing.

If the `thead` content isn't changing, target the `tbody` instead:

```js
$('#datazone tbody').html(feedback).trigger('update');
```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
