### ISSUE TITLE
Error on sort a column using TableSorter widget with a BootStrap Theme (show a lot of arrows icons when sort a column)

### ISSUE THREAD

**Issue by atovarlanz** [Mottie/tablesorter#1223]
Hi.

I found a demo code from tablesorter widget on https://mottie.github.io/tablesorter/, but when a use this widget with bootstrap theme when sort a column have a issue, in the headers  of unclicked columns show a lot of arrows icons. I attach a fiddle with this demo. https://jsfiddle.net/artovarl/gmrnqo4z/

I hope your help, thanks a lot

**Comment by Mottie** [comment]
The reason why the arrows are messing up in that demo is because that demo is really old. The code that extends the `uitheme` widget's class definitions (at the bottom of the javascript frame) is targeting the header cell and not the icons.

If you replace these `sort` definitions:

```js
$.extend($.tablesorter.themes.bootstrap, {
  // ...
  sortNone: 'bootstrap-icon-unsorted',
  sortAsc:  'icon-chevron-up',
  sortDesc: 'icon-chevron-down',
  // ...
});
```

with these `icon` definitions, it will work ([demo](http://jsfiddle.net/Mottie/gmrnqo4z/1/)):

```js
$.extend($.tablesorter.themes.bootstrap, {
  // ...
  // class name added to icon when column is not sorted
  iconSortNone: 'bootstrap-icon-unsorted',
  // class name added to icon when column has ascending sort
  iconSortAsc: 'icon-chevron-up glyphicon glyphicon-chevron-up',
  // class name added to icon when column has descending sort
  iconSortDesc: 'icon-chevron-down glyphicon glyphicon-chevron-down',
  // ...
});
```

Note: The `icon-chevron-up` and `icon-chevron-down` classes were left in to support those who are still using [Bootstrap v2](http://getbootstrap.com/2.3.2/).

**Comment by atovarlanz** [comment]
Thanks a lot, also see a demo i can see the implementation commented for you in http://jsfiddle.net/Mottie/z8Lacguz/
