### ISSUE TITLE
Sorting Accented Characters

### ISSUE THREAD

**Issue by camohub** [Mottie/tablesorter#1228]
Hello, I have a problem with accented characters. As I see in documentation  https://mottie.github.io/tablesorter/docs/example-locale-sort.html tablesorter should have default characterEquivalents table which is able to recognize character Č. But it does not. 
I have set sortLocaleCompare to true but Č is always at the and of table.
What could be the problem? Can you help me please? 
Thanks.

**Comment by Mottie** [comment]
Hi @camohub!

I created [this demo](http://jsfiddle.net/r25tag6k/5/) and it appears that the Č character is replaced with a unaccented "c". I added the `debug` option so that can be verified by looking in the console.

I'm not sure why you've encountered a problem, but if you would please modify the demo provided with data that duplicates the issue, it would make it easier for me to troubleshoot. Thanks!

**Comment by camohub** [comment]
Thanks, I will check it.

**Comment by camohub** [comment]
I am very sorry, I used this repository https://github.com/christianbach/tablesorter in my project. You have the same logo in documentation and Google show me your documetation. I am sorry. Now I have this fork and everything works well. Thanks.

**Comment by camohub** [comment]
Hi there, I founded out that Č is ok but what about Š,Ř or Ž?

**Comment by Mottie** [comment]
If you look at the [main demo](https://mottie.github.io/tablesorter/docs/example-locale-sort.html), it shows how to add more values to the `$.tablesorter.characterEquivalents` reference.

Here is an example ([demo](http://jsfiddle.net/Mottie/r25tag6k/10/))

```js
$.extend($.tablesorter.characterEquivalents, {
  "r": "ř",
  "R": "Ř",
  "s": "š",
  "S": "Š",
  "z": "ž",
  "Z": "Ž"
});
$(function() {
  $("table").tablesorter({
    debug: true,
    theme: 'blue',
    // Enable use of the characterEquivalents reference
    sortLocaleCompare: true
  });
});
```

Alternatively, and maybe a better solution since it sounds like you might be sorting a Czech alphabet... you can switch the sorting algorithm to use Sugar js... see the documentation on sorting the [Czech alphabet](https://github.com/Mottie/tablesorter/wiki/Language#czech).

**Comment by camohub** [comment]
Yes I have it. Thank you very much.
