### ISSUE TITLE
provide some help for counting adjacent rows on screen

### ISSUE THREAD

**Issue by anionic** [Mottie/tablesorter#1233]
A user asked if displayed table rows could be numbered from 1, unaffected by sorting; turns out she wants some help counting qty of rows in some contiguous range after she has sorted, and would happily do the mental arithmetic on the indices of the first and last rows of interest to her (counting on screen with a toothpick is unreliable & fatiguing if she has to scroll the viewport).

I can't implement this with what I know of the available options - does anyone have any ideas?

**Comment by Mottie** [comment]
Hi @anionic!

If you look on the [home wiki page](https://github.com/Mottie/tablesorter/wiki#widgets) there are a bunch of demos. Under Widgets > Other, you'll find three demos that add a widget which apply automatic row numbering. I'm didn't link them here since I'm not sure if you're using a pager or not.

**Comment by anionic** [comment]
Mottie

OK, so there's a widget for that ;-)

I'm not using a pager (yet) so I'll use "numbering"

Many thanks
