### ISSUE TITLE
Issue with data-value and filter-select at the same time

### ISSUE THREAD

**Issue by Jade124889** [Mottie/tablesorter#1271]
Using data-value to set a default filter works fine for a regular filter box, but when I combine with the a drop-down filter it seems not to work - anything special I should try or is this simply not supported?

**Comment by Mottie** [comment]
Hi @Jade124889!

It works for me. I created [this demo](http://jsfiddle.net/bbxxomhx/107/) to demonstrate the use of:

* [`filter-select`](https://mottie.github.io/tablesorter/docs/example-widget-filter.html#classes) class name to convert the filter into a select dropdown.
* [`filter-match`](https://mottie.github.io/tablesorter/docs/example-widget-filter.html#classes) class name to only match the results in the table. This defaults to an exact match otherwise.
* `data-value` which sets the initial query. The data-attribute can be changed by setting the [`filter_defaultAttrib` option](https://mottie.github.io/tablesorter/docs/#widget-filter-defaultattrib).
* [`filter_selectSource`](https://mottie.github.io/tablesorter/docs/#widget-filter-selectsource) mostly because I wanted to show more than one result.

```html
<th data-value="abc" class="filter-select filter-match">AlphaNumeric</th>
```

```js
$(function() {
  $('table').tablesorter({
    theme: 'blue',
    widgets: ['zebra', 'filter'],
    widgetOptions: {
      filter_selectSource: {
        0: ['abc', 'zyx']
      }
    }
  });
});
```

**Comment by Jade124889** [comment]
Thanks @Mottie - I can see it working perfectly there :) Your hard work is very much appreciated :)

I will do some further testing when I get a chance to see where it is coming unstuck. I am using quite a few widgets, and paging as well, all in a bootstrap 3 environment.

widgets : [ "uitheme", "filter", "columnSelector", "resizable" ]

Cheers
Chris

**Comment by Mottie** [comment]
Any update on this issue?

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Comment by Jade124889** [comment]
Sorry Rob, have been too busy to fully solve it. It has something to do
with the way I am dynamically loading the data.

**Comment by kratsg** [comment]
Sorry to necro this, but I find that this isn't working anymore. the jsfiddle doesn't seem to be functional, and when I use the code mentioned above, I am unable to get a default value selected with the dropdown. Can you advise? I cannot find any current working examples.

Specifically, when using the filter_defaultAttrib, it does not work -- but using `data-value` does appear to work :)
