### ISSUE TITLE
cssIcon does not work properly

### ISSUE THREAD

**Issue by camohub** [Mottie/tablesorter#1272]
Hi, I would like to show fa sort icons in header. So I have this in settings option:
```
$("#sortTable").tablesorter({
	debug: true,
	dateFormat: 'pt',
	sortLocaleCompare: true,
	theme: 'blue',
	cssIcon: 'fa fa-sort',
	cssIconAsc: 'fa fa-sort-asc',
	cssIconDesc: 'fa fa-sort-desc',
	headerTemplate: '{content} {icon}'
});
```
Asc and desc icons are displayed correctly, but default "fa fa-sort" not. It creates only class="fa-sort" in the &lt;i&gt; tag without first fa.  Is it a bug or am I doing something wrong?

**Comment by camohub** [comment]
As I finded out it should be
```
$("#sortTable").tablesorter({
    debug: true,
    dateFormat: 'pt',
    sortLocaleCompare: true,
    theme: 'blue',
    cssIcon: 'fa fa-sort',
    cssIconAsc: 'fa-sort-asc',
    cssIconDesc: 'fa-sort-desc',
    headerTemplate: '{content} {icon}'
});
```
This works.

**Comment by Mottie** [comment]
Hi @camohub!

Yes, the actual problem is that the `cssIcon` is only applied on initialization. To add an unsorted icon, use the [`cssIconNone` option](https://mottie.github.io/tablesorter/docs/#cssiconnone) instead.

```js
$("#sortTable").tablesorter({
    debug: true,
    dateFormat: 'ddmmyyy',
    sortLocaleCompare: true,
    theme: 'blue',
    cssIcon: 'fa',
    cssIconAsc: 'fa-sort-asc',
    cssIconDesc: 'fa-sort-desc',
    cssIconNone: 'fa-sort',
    headerTemplate: '{content} {icon}'
});
```

Also, note that the [`dateFormat` option](https://mottie.github.io/tablesorter/docs/#dateformat) for this fork does not support `"pt"` as an option. Only the [original tablesorter](https://github.com/christianbach/tablesorter/blob/master/jquery.tablesorter.js#L992) hosted here on GitHub supports that; not even the version you get from [`tablesorter.com`](http://tablesorter.com/) supports this option.

**Comment by camohub** [comment]
Thank you.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
