### ISSUE TITLE
Sorting Issues

### ISSUE THREAD

**Issue by lurajon** [Mottie/tablesorter#1289]
Hi,

I have a very strange problem, and I do not see the what causes it. I have a list of objects that are inserted into the table. From the server the data is sorted, but in the tablesorter, it is not.

![screen shot 2016-09-22 at 11 43 50](https://cloud.githubusercontent.com/assets/1674209/18743612/210dd3c6-80ba-11e6-99c5-47312186199c.png)

This is however not consistent. If I choose other data, everything is working as expected.

![screen shot 2016-09-22 at 11 47 04](https://cloud.githubusercontent.com/assets/1674209/18743655/593015e8-80ba-11e6-84b5-90b4b1d13edc.png)

This is my code:

```
$('#selected-cells') .tablesorter({
                      theme: 'bootstrap',
                      headerTemplate : '{content} {icon}', // new in v2.7. Needed to add the bootstrap icon!
                      headers: { 0: { sorter: false}, 1: {sorter: false}, 2: {sorter: false}, 3: {sorter: false}, 4: {sorter: false}, 5: {sorter: false}, 6: {sorter: false}, 7: {sorter: false}, 8: {sorter: false}, 9: {sorter: false}, 10: {sorter: false}, 11: {sorter: false} },
                      widgets: ['uitheme','zebra', 'pager'],

                      widgetOptions : {
                          zebra : ["even", "odd"],
                          pager_selectors: {
                            container   : '.pager',       // target the pager markup (wrapper)
                            gotoPage    : '.gotoPage',    // go to page selector - select dropdown that sets the current page
                            pageDisplay : '.pagedisplay', // location of where the "output" is displayed
                            pageSize    : '.pagesize'     // page size selector - select dropdown that sets the "size" option

                          },

                    }
                }).tablesorterPager({
                    container: $('.pager'),
                          pageReset: 0,
                          page: 0,
                          size: 50,
                          removeRows: false
                }).bind('updateComplete', function (e, c) {
                 updateDownloadButtonStatus();
    });
```

Best regards

Jone

**Comment by Mottie** [comment]
Hi @lurajon!

If the first item in the "AR4PI297" column is a pure number (e.g. "1234567"), then the parser will assume that the entire column only contains numbers. Make sure to set the parser to "text".

```html
<th class="sorter-text">...</th>
```

If you mean that "AR30419A" is after "AR4PP175", it's because the natural sort breaks the value into chunks, "AR-30419-A" and "AR-4-PP-175". In this case, 4 is greater than 30419. You might therefore want to use a plain (not natural) text sort. To do this, use the [`textSorter` option](https://mottie.github.io/tablesorter/docs/#textsorter) as follows ([demo](https://jsfiddle.net/Mottie/bbxxomhx/155/)):

Header cell HTML

```html
<th class="plainsort">AlphaNumeric</th>
```

```js
$(function() {
  $('table').tablesorter({
    theme: 'blue',
    widgets: ['zebra'],
    textSorter: {
      '.plainsort': $.tablesorter.sortText
    }
  });
});
```

Also, from looking at the code provided:

* Are you using the pager addon or widget? I see code for both, but only one is needed. I would recommend using the widget but really there isn't a difference.
* I see there are a lot of disabled columns in the `headers: { 0: { sorter: false},... 11: {sorter: false} }` option. An easier way to set this up is to add a "sorter-false" class name to the header

    ```html
    <th class="sorter-text">...</th>
    ```

  or, add any other class name to each header, something like "disabled", then use the `headers` option as follows:

    ```js
    headers: { ".disabled": { sorter: false } }
    ```

**Comment by lurajon** [comment]
Hi @Mottie !

This helped a lot. I did however needed to upgrade to the latest and greatest version to enable the textSorter.

All the mess in the code was written in frustration, and is now clean and neat

Best regards,

Jone

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
