### ISSUE TITLE
zebra stripes don't get applied if TABLE is contained in DIV with style=display:none

### ISSUE THREAD

**Issue by hmundt** [Mottie/tablesorter#1298]
Thank you for the work on tablesorter.

I have a table inside a div inside another div:

```
<div class="box closed">
    <div class="inside">
        <table id="thetable">...</table>
    </div>
</div>
```

The inner div will initially have display:none if the outer div has the class "closed", in which case the whole table will not be visible. zebra stripes are working OK only if the table is not contained in invisible elements while tablesortifying. Ideally, the zebra classes should still be applied if the table is contained in invisible elements.

I think this is caused by the way jQuery's CSS selector extension ":visible" is used in the logic that finds the rows that should get applied the zebra classes in jquery.tablesorter.js:2728 :

```
$visibleRows = $tbodies.eq( tbodyIndex ).children( 'tr:visible' ).not( c.selectorRemove );
```

Probably not too hard to fix, my time and knowledge of jQuery and tablesorter's internals is lacking too much though. Perhaps I could trigger an "applyWidgets" event to all tablesortified tables contained in the div when the div becomes visible but I feel like that would be a dirty workaround.

Not critical for me right now, after all it's just an UI thing. The other widgets I'm using here (saveSort, filter, resizable, stickyHeaders) seem to be initialized OK when the table is contained in an invisible element while tablesortifying.

**Comment by hmundt** [comment]
In less words: initialization of zebra widget should not depend on visibility of the table's parent elements.

**Comment by hmundt** [comment]
thinking out loud, perhaps the default behavior should not be changed but instead the requested change in behavior should be offered as an option to the zebra widget to ensure backwards compatibility

**Comment by Mottie** [comment]
Hi @hmundt!

Sorry for the delay in responding, I've just returned from a much needed extended vacation.

The zebra widget's behavior is as intended. The recommended method to apply/update the zebra stripes is as you described:

> Perhaps I could trigger an "applyWidgets" event to all tablesortified tables contained in the div when the div becomes visible but I feel like that would be a dirty workaround.

The main reason why the zebra class names are applied to only visible rows is because of filtered rows, paged rows, and rows or entire tables hidden by other methods. If a table is hidden inside of a div, or tab, as described, there is no easy way to determine if a row is to be hidden or visible if the pager is applied. Utilimately, I still think the best solution is to refresh the widget once the table becomes visible.

**Comment by hmundt** [comment]
Thank you for the explanation. I hope you had a good vacation!
