### ISSUE TITLE
Pager not working in edge version 14

### ISSUE THREAD

**Issue by ploureiro** [Mottie/tablesorter#1303]
Apparently the pager is not working in the new version of "**Microsoft edge html 14**"  in windows 10.

Tested with the following demo under **edge 14** and doesn't work: [https://mottie.github.io/tablesorter/docs/example-widget-bootstrap-theme.html](https://mottie.github.io/tablesorter/docs/example-widget-bootstrap-theme.html)

**behaviour**: keeps reloading the page until an error happens.

Cheers,
Patrick

**Comment by themilkman** [comment]
I just wanted to open a new issue, but I think my problem is related to yours. After disabling the pager it worked for me too. To me this is strange as the pager example pages in the docs work. Might it be related to pager+theme or so? 

Here my original post:

---

Hi,

in a few projects of mine I noticed problems with tablesorter and Win10/latest version of the MS Edge Browser.

What worked in older versions (at least at 25.10586.0.0/13.10568 or so) of Edge and also in IE 11 (as well as in Chromium, Firefox and even Safari on Linux/Mac) now leads to a total 'render crash' in the latest version:
Microsoft Edge 38.14393.0.0  / Microsoft EdgeHTML 14.14393

Since I am a Linux user it is difficult to get deeper into it. Also, Edges behaviour (redirect to plain error page, no way back, dev-console cleared) made it really difficult for me to determine the source of this issue (except only blaming MS of course ;-P).
But (for me fortunately) this error also appears in the documentation pages of tablesorter:

https://mottie.github.io/tablesorter/docs/example-option-theme-metro-style.html
https://mottie.github.io/tablesorter/docs/example-widget-bootstrap-theme.html


This example (and many others) work:
https://mottie.github.io/tablesorter/docs/example-widget-ui-theme.html

I tested it on a few computers, it is reproducable (well, just for completeness, I tested via an IPv6 connection but I do not hope, that this is related at all ;)).
I am using the Bootstrap 3 theme, mostly those widgets: ['uitheme', 'filter', 'resizable'], the pager (addon) and a few specific features. But I do not think that this is related to the problem itself. Otherwise I also could post my tablesorter script. The scripts are all 'locally', no CDN or so in between.
Also I went back the first tablesorter version of 2015 - same issue.

Can anyone confirm this issue and give some advice? Thanks in advance for any feedback. I'll try to test ideas/give any information but my access to affected Windows PCs is quite limited.

Cheers,
Erik

**Comment by ploureiro** [comment]
I confirm your analyse @themilkman, it seems a bug in the pager sorter. 
It all works fine under edge 14 if you disable the Pager completely. (tablesorterPager)

So, for now just **disable the pagination** to keep using tablesorter, until the bug is fixed.

**Comment by Mottie** [comment]
Hi @ploureiro & @themilkman!

Sorry for the long delay in responding, I've been on an extended vacation.

That is very odd and extremely difficult to troubleshoot. Thanks MS!

I think the problem might be related to the widgets re-rendering the table more than once during initialization. I'll try to spend more time isolating the problem once I catch up with my other work.

**Comment by themilkman** [comment]
Hi @Mottie!

Yeah, I believe this is ah typically MS-pain :-/ Did you anyway had the chance to take a look into this? I expect the group of people affected by this is constantly growing (even although it is an MS Browser ;-)) and I fear I'll soon get confronted with this by some customers of our projects. Unfortunately I have no idea how to dig into this to solve it / have find a workaround. I'd be very happy to get this solved - but of course I know, you haven't not much free time. If I can support you in any way besides testing please let me know.

Thank you for all your work on this great library and efforts!!

**Comment by Mottie** [comment]
I think the problem is that the widget code is called multiple times, so if you use the pager AND multiple widgets Edge things it's stuck in recursion and aborts. If you use the pager, you may have to be careful which widgets are included.

Edge made this issue insanely difficult to troubleshoot since it aborts to a different page and there is no way to see what javascript code caused the issue... the inspector doesn't work and code breaks don't seem to help.

I think the solution would be to add an internal promise que that can remove repeated function calls and manage the order of the que, like move higher priority calls to the front of the que. I have yet to find, or create such a system. The sad thing is that I have some time now, but I lack the knowledge and motivation to work on such a system. And even if I implement this system, I'm not sure it will solve this Edge browser issue. *sigh*

**Comment by themilkman** [comment]
Hm, yes, I do totally understand that this sucks.

I hope an Edge will revert this internal change and thus solve issue. Otherwise I might be forced to switch the table library :-( 
When I have a little bit free time I'll try to investigate once more in this issue.

**Comment by Mottie** [comment]
Sorry, even though I have some free time now, I have a lot going on. o.O

I'll try to spend some time on this issue very soon...

**Comment by Mottie** [comment]
Ok, this is really odd...

For now, if you need the pager to work in Edge, move the pager controls outside of the table. Adding the controls inside the table is the cause of the crash.

* [crashing demo](https://jsfiddle.net/z8Lacguz/27/)
* [working demo](https://jsfiddle.net/z8Lacguz/27/)

The only difference between the two demos is the "pager" is under the table in the second demo instead of in the `tfoot` as seen in the first.

Now I just need to isolate the reason and fix it!

**Comment by Herst** [comment]
What an odd bug, and I can't find anything on it at MS's bug tracker: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/?page=1&q=ariaDisabled

**Comment by Mottie** [comment]
Yeah, I don't know why using `.attr('aria-disabled')` was breaking Edge. When I switched it to `.prop('aria-disabled')` it worked beautifully. Even stranger, I could not reproduce the crash using JSFiddle and a basic table with buttons inside.

**Comment by themilkman** [comment]
Thank  you soooo much for your work @Mottie !  :tada: What a strange behaviour of Edge, great that you found it. :+1: 
I'll use your updated version asap next week. Thanks again :)
