### ISSUE TITLE
Tablesorter: Editable and Scroller widgets together

### ISSUE THREAD

**Issue by wall-s** [Mottie/tablesorter#1304]
I have an application where I'm using the tablesorter scroller widget to keep headers and 2 columns fixed. I also have a requirement to edit the content in one of the fixed columns if necessary. Naturally I thought I would try using the editable widget included with tablescroller.

So, I set up my code to use the editable widget in addition to the scroller, and the editable widget did make the content of the cells editable, but there was no way I could trigger the "editComplete" event, even when following the provided examples. I spent a couple hours trying to write the binding ".on()" in different ways, but to no avail. Finally, to satisfy my curiosity, I removed all the "widgetOptions" related to the scroller, and the editable widget started working.

I'm wondering, are there any known issues with scroller and editable being defined in the same code? Or if there might be any other widget incompatibilities?

Thanks in advance for your time.

**Comment by Mottie** [comment]
Hi @wall-s!

Sorry for the long delay in responding, I've been on an extended vacation.

Thanks for reporting the problem. I'll take another look at the compatibility between the editable and scroller widgets once I catch up with on all the new issues.

The editable widget uses delegated event bindings on the table, but it's been a while since I looked at the code, so I don't remember if that event binding also applies to the scroller widget cloned header blocks.

**Comment by imanasardar** [comment]
Hi

**Comment by imanasardar** [comment]
use this: 
 widgets: ['scroller', 'editable'],

**Comment by Mottie** [comment]
The scroller is currently incompatible with the editable widget. I've centralized all of the scroller widget incompatibilities into one issue (#1487). Please follow any progress there.
