### ISSUE TITLE
Prevent column from first head row from sorting

### ISSUE THREAD

**Issue by flinhardt** [Mottie/tablesorter#1326]
Hi, I do have a tablesorter table with two rows in my head and would like to prevent sorting by clicking the columns in the first row. Help would be great! Thank you very much!

**Comment by Mottie** [comment]
Hi @flinhardt!

To disable the sort in a column, or specific header cell, add a class name of `sorter-false` ([demo](https://mottie.github.io/tablesorter/docs/example-options-headers.html)).

To completely disable a row, add a class name of `tablesorter-ignoreRow` to the `tr`. This class name is set by the [`cssIgnoreRow` option](https://mottie.github.io/tablesorter/docs/#cssignorerow).

And please, the next time you have a question, use one of the support methods listed in the [main readme](https://github.com/Mottie/tablesorter#questions), instead of opening an issue. Thanks!

**Comment by flinhardt** [comment]
Ok. Thanks for your help and sorry for opening posts in here.
