### ISSUE TITLE
Does it work with JQuery mobile?

### ISSUE THREAD

**Issue by PolHaghverdian** [Mottie/tablesorter#1329]
Hi,

It is unclear in the documentation if the plugin works with JQuery mobile?

**Comment by Mottie** [comment]
Hi @PolHaghverdian!

Yes, jQuery Mobile still requires jQuery.

If you need to modify the class names of the table add them to your HTML. Or add a `data-theme` as needed. For tablesorter specific classes, modify the [configuration options](https://mottie.github.io/tablesorter/docs/#Configuration) that start with `css`.

Also make sure to initialize the code using [`pagecreate`](https://api.jquerymobile.com/pagecreate/) instead of a document ready function:

```js
jQuery(document).on("pagecreate", function() { 
  jQuery("table").tablesorter();
});
```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
