### ISSUE TITLE
tablesorter -- master // ipv4 and network parser

### ISSUE THREAD

**Issue by thezoggy** [Mottie/tablesorter#1344]
ipv4 parser doesnt look like it works anymore until you use the network parser...

https://mottie.github.io/tablesorter/docs/example-parsers-ip-address.html
`		<li>The default "ipAdress" parser (IPv4) is included with the original tablesorter; it was moved to the <code>parser-network.js</code> file in <span class="version">v2.18.0</span>.</li>`

was that supposed to say 'is NO LONGER included'?

loading the network parser I see:
```
TypeError: ts is undefined
file:///F:/test/js/parsers/parser-network.js
Line 17
```

**Comment by Mottie** [comment]
Hi @thezoggy!

Yes, I moved the `ipAddress` parser into a separate file and replaced it with an `image` parser since it is much more common. I should make that change more obvious... or add it back?

The network parser should be loaded after tablesorter. I think that is why you're seeing that error. `ts` is defined on line 7: `var ts = $.tablesorter`.

**Comment by thezoggy** [comment]
yep thats what it was. yeah once i loaded the parser js then the ipv4 parser works. the docs just made it sound like i only needed the parser for v6..
