### ISSUE TITLE
Freeze / Fixed Left Columns on Horizontal Scroll

### ISSUE THREAD

**Issue by nugie73** [Mottie/tablesorter#135]
I am using jQuery TableSorter for my Report Component at Joomla 2.5.6 framework. It is working great!

Now my component needs to be able to create a dynamic table with many columns, which I need to enable a horizontal scroll. I need to have at least one or two freeze/fixed column(s) on the left,  something like sticky-headers, but this is sticky-left-columns I might call.

I wonder if the TableSorter has this feature? If it has, kindly please assist me how to configure it.  

Thank you in advance for your kind help.

**Comment by philberg24** [comment]
Can't wait until March 2015 ;-)

**Comment by Mottie** [comment]
Yes, and I hope to make setting the number of fixed columns dynamic so a user can lock or unlock a column.

**Comment by philberg24** [comment]
Great. Another challenge for you. If you look at : 
https://datatables.net/extensions/fixedcolumns/

You will notice that the row highlight is not working properly. Fixed colums have their "own" highlight. If you would be able to highlight the entire row, that would be great, as well as highlighting in same time the column (on mouse over). :)

**Comment by mworsnop** [comment]
Thanks for the message Mottie. Very anxious to get this new feature.  Thank you for such a cool tool!

**Comment by Mottie** [comment]
Check out the last table in the [scroller widget demo](http://mottie.github.io/tablesorter/docs/example-widget-scroller.html#group)... :grinning:

**Comment by dqduc** [comment]
Very nice job

**Comment by Francks11** [comment]
Hello Mottie,

the scroll widget is not include in jquery.tablesorter.widgets.js?

Where can i download this widget?

Can you give me a simple example in http://jsfiddle.net?

The example here http://mottie.github.io/tablesorter/docs/example-widget-scroller.html#group does not explain the minimal code need for this.

Thank you very much.

**Comment by Mottie** [comment]
Hi @Francks11!

No, the scroll widget is not included in the "jquery.tablesorter.widgets.js" file. You can see what is included in that file, by default, in the main documentation under [Demos](http://mottie.github.io/tablesorter/docs/#demos) and looking for the red dagger &dagger;

To get all the files, you can go to the [Download section](http://mottie.github.io/tablesorter/docs/#Download) in the main documentation, or on the [main repository page](https://github.com/Mottie/tablesorter), you can download everything by clicking on the "Download ZIP" button. I would recommend updating all the files, meaning the core & other widgets you are using.

If you already have everything updated and only need the scroller widget, go to the file in the repository directly: https://github.com/Mottie/tablesorter/blob/master/js/widgets/widget-scroller.js. Click the "Raw" button and download it from there.

Here is a [fiddle](http://jsfiddle.net/Mottie/856bzzeL/143/) - while creating it, I have no idea why it works so beautifully on the main demo page, but looks like crud in the fiddle... I'll have to look at the code again later today.

As for the minimum code required, this needs to be in the header:

```html
<script src="js/jquery-latest.min.js"></script>
<link rel="stylesheet" href="css/theme.blue.css">
<script src="js/jquery.tablesorter.js"></script>
<script src="js/jquery.tablesorter.widgets.js"></script>
<script src="js/widgets/widget-scroller.js"></script>
```

and the initialization code:

```js
$(function(){
	$('table').tablesorter({
		theme: 'blue',
		widgets: [ 'zebra', 'scroller' ],
		widgetOptions : {
			scroller_height : 300,
			scroller_fixedColumns : 2
		}
	});
});
```

**Comment by Francks11** [comment]
Thank you for your help :-)

When I remove filter from widgets, the fixed columns do not work. Is this normal?

Link : http://jsfiddle.net/856bzzeL/144/

Thank.

**Comment by mspencer** [comment]
Hi Mottie

Thanks for working hard to release this new widget, it's very very useful.

There're a few issues I found: 
- the fixed columns td is taller than the table's td
- the widget has a funny relationship with filter widget, ie. the filter widget stops working as soon as implemented this plugin

Please don't be discouraged by all these though, it is a very useful plugin indeed :)

Thanks a lot.

**Comment by Mottie** [comment]
@mspencer Thanks!

The filter widget works for me... and it works in the [scroller demo](http://mottie.github.io/tablesorter/docs/example-widget-scroller.html#group). Please make sure to update all of your widgets to the most current version.

**Comment by Mottie** [comment]
@Francks11 

The jsFiddle is acting very strangely... I'm not sure why it's not working properly. If I do not include the filter widget in the main scroller demo, it works perfectly.

**Comment by Mottie** [comment]
Ok, I found the problems...

* The jsFiddle is using jQuery edge version... apparently there are issues with determining widths.
* The following css also needs to be added to make everything line up perfectly

    ```css
    *, *:before, *:after {
       -moz-box-sizing: border-box;
      -webkit-box-sizing: border-box;
      box-sizing: border-box;
    }
    ```

Try this demo: http://jsfiddle.net/Mottie/856bzzeL/145/

**Comment by Francks11** [comment]
Ok thank you very much.

When i upgrade to the last version of tablesorter and widget, the sticky header does not work anymore and I have this error in javascript console :

TypeError: c.$headerIndexed[col] is undefined
Line : 610 of tablesorter file.

Why? If a take the old version 2.8.2, its works.

Thank you for your help :-)

**Comment by Francks11** [comment]
On some tables, its works but with last version, caption of table is in the sticky header unlike the version 2.8.2.

**Comment by Mottie** [comment]
@Francks11 Is the javascript error still an issue? `c.$headerIndexed` was added in v2.21.0. If you keep the core and all the widgets up-to-date, there shouldn't be any problems.

**Comment by dqduc** [comment]
The tips "box-sizing" worked great. It cover nearly all align issues.
One thing I noticed is the pointer-events was set to "none" by default in fixed columns (css 'tablesorter-scroller-fixed'). It somehow made links in fixed columns/cells un-clickable, including sorting.
So what is the purpose of this settings ? Is it affect anything if I try to override it ?
Thanks

**Comment by Mottie** [comment]
Hi @dqduc!

I disabled pointer events for a specific reason while working on the code... honestly, now I don't remember why it was necessary. To test it, I went in and removed that line from the added css and the fixed column text was still unselectable. I'll have to look at it in more depth when I get some free time.

**Comment by dqduc** [comment]
I defined some css to override it, and the fixed column feature still work good (with select-able cells in fixed columns):

.tablesorter-scroller-fixed th, .tablesorter-scroller-fixed td {
        pointer-events: all;
}

**Comment by Francks11** [comment]
Hello Mottie,

I try to use Fixed Columns according to your procedure but its doesn't work for me :-(.

The horizontal scrollbar is present but grayed...

Why?

I have update all scripts.

![capture](https://cloud.githubusercontent.com/assets/3995851/7248689/fce310c2-e814-11e4-8ca0-f6bb4416e5c4.png)

**Comment by Mottie** [comment]
Hi @Francks11! 

Did you try setting the box sizing? What browser is that? And if that doesn't work, please update [this demo](http://jsfiddle.net/856bzzeL/149/) with the script & table, and the width of the table so I can duplicate and troubleshoot the problem.

Thanks

**Comment by Francks11** [comment]
Ok Mottie. I found the bug.

When the table is contained in other tables, the fixed columns do not work.

You can found a example here : http://jsfiddle.net/856bzzeL/150/

I have juste surrounded table by <table><tr><td></td></tr></table>

I'm working on a portal and portlets are surrounded by tables and I can't remove the tables.

Can you help me? Do a fix to the js?

Thank you.

**Comment by Francks11** [comment]
It is a know bug?

**Comment by Mottie** [comment]
If you're asking if I knew about it before, no.

How is the outer table width being limited? In that demo, the inner table is pushing the width of the outer table beyond the width of the window, so it's not limiting the size. Please update the demo with the method you are using to limit the outer table width, and I'll look at it again.

**Comment by Francks11** [comment]
You can find here a simple example based on your demo: http://dl.free.fr/kP4DIPNJQ (test.html)
I just add outer table.

I don't understand what you mean... Can you explain me how to do fixed columns works with my example? I try to set outer table width, inner table width, but it doesn't work...

Can you help me?

Thank you.

**Comment by Francks11** [comment]
Ok @Mottie, I understood how to use fixed columns.

I have set following css style to outer table and its works:

<table style="table-layout: fixed; width: 700px;">
	<tr>
		<td>
			<table id="fixed-columns-table">
				<thead>
					<tr>
						...
					</tr>
				</thead>
				<tbody>
					<tr>
						...
					</tr>
				</tbody>
			</table>
		</td>
	</tr>
</table>

Link for demo : http://jsfiddle.net/856bzzeL/159/

Thank

**Comment by Francks11** [comment]
Why this css is not include automatically by js on init?

```
 html {
  box-sizing: border-box;
}
*, *:before, *:after {
  box-sizing: inherit;
}

#fixed-columns-table tbody td {
	/* force "Notes" column to not wrap, so we get a horizontal scrolling demo! (optional css) */
	white-space: nowrap;
	/* Add min column width, or "Index" column filter gets too narrow to use (optional css) */
	min-width: 60px;
}
```

**Comment by Francks11** [comment]
Bug or not bug?

The vertical scrollbar is very slow when we use the mouse wheel...

**Comment by Mottie** [comment]
The box-sizing css is not automatically added because that is left to the developer to decide if they want to add a global css setting. I guess I could add a `border-box` size definition that specifically targets tables with the scroller widget applied.

The last bit of css that prevents word wrapping is completely optional, and again left up to the developer to decide if it should be included or not.

If you read the ["Notes" section for v2.21.3 on the scroller widget demo page](http://mottie.github.io/tablesorter/docs/example-widget-scroller.html#notes), you'll see the following:

> * Yes, there are some alignment & padding issues when using the jQuery UI theme with a fixed column, I'll look into resolving this; all other themes are nearly pixel perfect.
* The fixed column widget includes extra css to prevent tbody cell content from wrapping (see the css code below); it was for demo purposes only, it is not a requirement.
* This update does not include optimizations to allow this widget to work with very large tables; so please be conscious of this fact.
* A lot of Firefox tweaks were needed to make it work! **I need to investigate why the mousewheel scrolling is so slow (at least in Firefox for Windows) when a fixed column is included**.
* There were lots of other tweaks to the core and other widgets (e.g. zebra & filter widgets) to get these changes to work seamlessly, so please make sure to update everything!

So, I haven't had time to figure out why Firefox has to be different and I can't duplicate the issue with the vertical scroll not being aligned... maybe it's the custom theme being used? Try removing the table bottom margin/padding.

Lastly, I'll push a change to make overflow use `auto` instead of scroll for the horizontal scrollbars; I won't change the vertical scrollbars as the width of the scrollbar is included in the overall table width.

**Comment by Francks11** [comment]
Ok thank you very much and I am sorry for any inconvenience.

The tablesorter is a very good tool, congratulations for your work :-).

I will see to fix the bug for firefox scrollbar if I have time.

Question, how can I set widget option after init?

Thanks

**Comment by Francks11** [comment]
Hello,

when I test fixed columns with Internet Explorer 9, a scrollbar appears in fixed columns :

![capture](https://cloud.githubusercontent.com/assets/3995851/7313335/57c09948-ea58-11e4-97a5-ecd4a3cf4c63.png)

You can test with your demo if you have internet explorer 9 :

http://jsfiddle.net/Mottie/856bzzeL/146/

How to remove it?

Thanks

**Comment by Mottie** [comment]
Ok IE9 should now hide the scroll bar. I didn't get a chance to fIx tabbing in header, since I've run out of free time for today.

To set widget options after tablesorter has initialized you can use the below code... some widget options can be changed dynamically, but not all. It would help if you specified which option you want to change because many widgets have a specific update method; but this is how to do it, **in general**:

```js
$('table')[0].config.widgetOptions.myWidgetOption = true;
$('table').trigger('applyWidgets');
```

The above is almost exactly the code found in the [`applyWidgets` method](file:///D:/Repos/tablesorter/docs/index.html#applywidgets) documentation... please search the documentation before asking questions. The more time I spend answering questions, the less time I have to work on code. You pick which one is more important to you.

**Comment by Francks11** [comment]
Hello,

how to force tablesorter scroller widget use full width available of browser, without set static width.

Currently I put the table sorter in following div with static width :
``` 
<div class="data-scrollable-table" style="width: 1200px;">
table sorter table here
</div>
```

I would like that table sorter takes all the space in width and if the table get out the screen, the horizontal scrollbar appears.

If the table sorter is smaller that browser width, it takes only the necessary place.

It is possible?

I have look at documentation and I have found nothing?

It is possible? It that clear?

Thank you.

**Comment by Mottie** [comment]
Hi @Francks11!

Please ask questions that are **not specific** to tablesorter on [Stackoverflow](http://stackoverflow.com/). This is a css issue that I could answer if I was not so limited on time.

**Comment by Francks11** [comment]
Hello @Mottie,

I answer my previous message.

The context :

I use tablesorter in WebSphere Portal. Applications are contained in portlets and portlets layout is performed with table, and I don't have hand on this.

The issue :

When table is contained in nested table, the table is not fit in available space in browser, the horizontal scrollbar doesn't appear and it is necessary to specify the width to do it works.

Example : http://jsfiddle.net/856bzzeL/266/

The solution

To do it works when table is contained in nested table, the table parent
must have table-layout css to fixed and width 100%.

Example : http://jsfiddle.net/856bzzeL/267/

We can leave the choice to the developer to add this css  : 

```
<table style="table-layout: fixed; width:100%">
	<tr>
		<td>
			TABLE SORTER TABLE
		</td>
	</tr>
</table>

```

In my case, it is not possible, because I have no hand on layout.

Solution 1 :

Add javascript code outside tablesorter to set table layout and width.

Solution 2 :

Integrate it into scroller widget. If you want integrate it in widget scroll.js, we can add the following code (available from my fork) :

https://github.com/Francks11/tablesorter/commit/c298bba34b7a455b1e3f4dbbc8adf44013a263e9
https://github.com/Francks11/tablesorter/commit/d4f56a2e245e9d178d81e047d5df3bdda9db73c8

I don't know if is the best solution to add this css to the table parent. What are the risks?

Maybe, if tablesorter table has a table parent, it would be better to create a table, which surround table sorter which have css : table-layout css : fixed and width : 100%. No? To avoid rendering modification.

:-)

**Comment by joshiegreer** [comment]
Hi @Mottie,

Not sure if this is the best place to post this, but I'm wondering if the new scroller release works with the pager plugin?  Everything seems fine when I implement without using pager, but comes apart when I do.  Any thoughts you have on this would be appreciated.

Josh

**Comment by Mottie** [comment]
Hi @joshiegreer!

The current version does not integrate well with the pager. There is some code in [issue #884](https://github.com/Mottie/tablesorter/issues/884#issuecomment-97051829) to make it work, but the columns do not line up on most pages.

@TheSin- has been helping me fix some of these issues, and we should be able to post an update soon. One that does work nicely with the pager.

The scroller widget still needs a lot of work before it can be used with [many of the other widgets](https://github.com/Mottie/tablesorter/issues/905#issuecomment-101264340). It's a slow process because of my time limitations.

**Comment by ilakkuvan** [comment]
@Mottie  @Francks11  I am alignment issue for scrolling (all browser).

please provide me better solution
![1021ea34-08bb-11e5-80d0-61ff9636e1ed](https://cloud.githubusercontent.com/assets/20130611/16343816/ec470f26-3a56-11e6-99e9-b6df284bfcfc.png)

**Comment by ilakkuvan** [comment]
@Mottie Iam facing problem for vertical scroll in IE

![](https://cloud.githubusercontent.com/assets/20130611/16343816/ec470f26-3a56-11e6-99e9-b6df284bfcfc.png)

**Comment by Mottie** [comment]
Hi @ilakkuvan!

Are you using the latest version of the scroller widget?

I am not seeing that same issue in Edge, even when emulating IE9 in [this demo](https://mottie.github.io/tablesorter/docs/example-widget-scroller.html) ([you shouldn't need to support any older versions of IE](http://www.pcadvisor.co.uk/how-to/software/what-you-should-do-now-that-internet-explorer-support-has-ended-3633266/)).

**Comment by ilakkuvan** [comment]
@i am using  Edge and ie10

**Comment by ilakkuvan** [comment]
i put height for .tablesorter-scroller-fixed tbody tr solves this problem

**Comment by ilakkuvan** [comment]
Please update correct solutions

**Comment by TheSin-** [comment]
can you make a demo that shows this issue, I feel like maybe you changed the font-size and not the line-height.

**Comment by dhruvJaiswal** [comment]
I dont know what is the problem with me. I am using datatables fixcolumn but it is not working initially but when i click on first column sorting symbol then it starts working can you tell me what is the problem.

**Comment by Mottie** [comment]
@dhruvJaiswal Sorry, we don't deal with datatables.

**Comment by Albion87** [comment]
hi @Mottie ,
i have a table which is freeze table header & first 2 columns
I'm having issues with scrolling,  when I expand child rows in my table, 
Left column [those are the 2 columns that I freeze using table sorter] and main body are not synchronized when scrolling up or down,
here's my script:

	        function freezingTableHeaderWithSorter() {
	            var $table2 = $('#fixed-columns-table').tablesorter({
	                theme: 'blue',
	                showProcessing: true,
	                headerTemplate: '{content}',
	                widgets: ['scroller'],
	                widgetOptions: {
	                    scroller_height: 410,
	                    scroller_jumpToHeader: true,
	                    //scroller_barWidth: null,
	                    scroller_fixedColumns: 2,
	                    scroller_addFixedOverlay: true,
	                    scroller_rowHighlight: 'hover'
	                }
	            });
	        }
Is there any attribute that i missed? any solution for this matter.

**Comment by suriyaJaay** [comment]
@Mottie . i've came across your demo from here [](http://jsfiddle.net/Mottie/856bzzeL/146/)

is that possible to freeze column based on user selection.?

**Comment by Mottie** [comment]
Hi @suriyaJaay!

Right now, no. The frozen columns are either added from the left (LTR) or right (RTL). There isn't a good column swapping method in place.
