### ISSUE TITLE
Select2 filter doesn't work with the scroller widget?

### ISSUE THREAD

**Issue by pineliu** [Mottie/tablesorter#1350]
Hello,

I tried to use the select2 filter together with the scroller widget, but it seems that because the scroller widget set the overflow:hidden for the header div, the select2 filter won't be able to show the result panel. Is there a way to fix this? Thank you very much!

Best wishes,
Pine

**Comment by Mottie** [comment]
Hi @pineliu!

Sorry no, the scroller widget is not compatible with a lot of widgets. The select2 library would need to be set to target the filters in the extra header... I haven't updated the scroller widget in a while because it is a complex and a pain to make it work across all browsers.

I'll add it to my to-do list, but I doubt I'll get to fixing it for a while.

**Comment by Mottie** [comment]
The scroller is only partially compatible with the filter widget. I've centralized all of the scroller widget issues into #1487. Please follow any progress there.
