### ISSUE TITLE
Add a composer.json file

### ISSUE THREAD

**Issue by spoonerWeb** [Mottie/tablesorter#1355]
Would be awesome to get your package via composer.

**Comment by Mottie** [comment]
Hi @spoonerWeb!

Will do... I'll get that file added soon!

**Comment by Mottie** [comment]
Hmm, when I tried to submit to Packagist, I get an error message:

> The CSRF token is invalid. Please try to resubmit the form.

First off I'm a php n00b... this [Stack Overflow answer](http://stackoverflow.com/q/23455780/145346) isn't very helpful since it is meant for Symfony2.

I did not include these sections in the `composer.json` ([ref](https://packagist.org/about#creating-a-composerjson-file)) since I wasn't sure what settings to use. Could this be the cause of the error?

```js
    "require": {
        "php": ">=5.3.0"
    },
    "autoload": {
        "psr-0": {
            "Monolog": "src"
        }
    }
```

**Comment by Mottie** [comment]
Wow, the original tablesorter has a fork with [this `composer.json` file](https://github.com/akiyatkin/tablesorter/blob/master/composer.json)....

```js
{
  "name":"christianbach/tablesorter"
}
```

Maybe I added too much? <img title=":_ bipolar :" src="https://cloud.githubusercontent.com/assets/136959/13512241/15d8362c-e15f-11e5-8c32-35b78deb9017.gif">

**Comment by Mottie** [comment]
Ok all set! https://packagist.org/packages/mottie/tablesorter
