### ISSUE TITLE
Pager sometimes not working

### ISSUE THREAD

**Issue by omriran** [Mottie/tablesorter#1358]
Hi guys,

I'm having issues where the pager sometimes not working and I can see only the next and previous images without actual page numbers. The data is being loaded and and the initial number of rows is right (set to 15) and the rest of the rows are hidden. I just don't see the page numbers. 

while debugging the problem i've notice that on the pager script that when the page numbers are missing the p.totalrows is 0 (instead of how many rows i've actually have). Is it a timing thing? Is it trying to set the number of pages before the data is loaded?

The weird thing is that sometimes it will load with page numbers on the first load and sometimes I need to hit reload a couple of times.

I'm also using the custom pager control. Initially I thought that this is the cause of the issue but it occurs when disabling it. 

Many thanks,
Omri

**Comment by omriran** [comment]
Hi,

Another thing I've notice is that when I'm using my reset function after the table is loaded the table pager is working

$('.reset').on('click', function () {
                $('.monitoringFilters').val('').trigger('keyup');
                $table.trigger(('enable') + 'Pager');
            });

**Comment by Mottie** [comment]
Hi @omriran!

Sorry for the long delay in responding. I've been away for the past 3 weeks.

> while debugging the problem i've notice that on the pager script that when the page numbers are missing the p.totalrows is 0 (instead of how many rows i've actually have). Is it a timing thing? Is it trying to set the number of pages before the data is loaded?

The page numbers are initially set to zero, but will update after content has been loaded by either the pager ajax settings or manually by triggering an "update" on the table.

I've seen this problem before, but it usually turns out to be a minor issue (I hope). I would be able to better help you if you would please share the initialization code, or modify [this demo](http://jsfiddle.net/Mottie/pj1bb2ao/) to show the problem you're describing. Thanks!

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
