### ISSUE TITLE
Number of Columns limit ?

### ISSUE THREAD

**Issue by lmwOnGitHub** [Mottie/tablesorter#1375]
I added a column to my table that was working just fine, but the last column now will not allow sorting.  I turned on debug to discover that that last index of 13 was not shown.  The exact error is 'Object doesn't support property or method 'replace'' in sortNatural.  If debugging it shows an object passed in instead of a value from the cell.  

Is it possible there is simply a limit on the number of columns we can have in the table?

**Comment by Mottie** [comment]
Hi @lmwOnGitHub!

There is no limit on the number of columns. To me it sounds like:

* The parser for the column in question might need to be set as "digit" instead of "text" as the sortNatural function does not convert numeric values into a string. This would cause the error you mention.
* Also, please make sure the HTML is not malformed... you can use http://htmlhint.com/ for a quick online check.

If neither suggestion works, please share a demo of this issue by modifying [this demo](https://jsfiddle.net/Mottie/bbxxomhx/) - please make sure to remove any sensitive data.

**Comment by lmwOnGitHub** [comment]
Thank you for the response.  I will work on getting you a demo and double checking the html and let you know.  In the mean time, for your information, the values in the column in question were single letter values, C or D.  Would digit apply in that case?
 
I also tried switching column order so that some other type of information was at that index and still had the same problem, text or money.  Any column past 14, index of 13, would not sort. I do agree that does sound like an html issue and that is the first thing i looked at, but I did not see anything odd, did not try the htmlhint.  I have other higher priority projects but will try to get back to this one ASAP.
 
Thank you again for the quick response.
 
-----Original Message-----
