### ISSUE TITLE
Exclude column from sorting

### ISSUE THREAD

**Issue by H4rdB4se** [Mottie/tablesorter#1421]
Hi,

is there any option to exclude one column from sorting?

I have a table like this
Rank | Name | Money | Age
1       | A        | 50000 | 54
2       | B         | 4400   | 32
3       | C         | 2549   | 21

And the first column which indicates the index should always stay in the same order. 
Is there any way to do this?

**Comment by Mottie** [comment]
Hi @H4rdB4se!

If you look at the [home wiki page](https://github.com/Mottie/tablesorter/wiki#widgets) under "Widgets" > "Other", there are two example widgets that can accomplish this:

* Automatic Row numbering ([with pager](http://jsfiddle.net/Mottie/4mVfu/1162/) & [without pager](http://jsfiddle.net/Mottie/abkNM/9/)).
* Automatic Row numbering with [values instead of an index](http://jsfiddle.net/Mottie/abkNM/2829/).

**Comment by H4rdB4se** [comment]
Yea, big thanks. Thats what i was looking for :)
