### ISSUE TITLE
Performance issue in IE 11

### ISSUE THREAD

**Issue by thayanithi** [Mottie/tablesorter#1422]
Facing Performance issue takes 10 sec to load 2000 rows in IE and Chrome 3 sec.
Used table sorter v2.25.4 also tried with the latest version of table sorter.   Also using custom page controls for pagination, 

Below are the  options used

```js
$table
  .tablesorter({
    theme: "blue",
    cssChildRow: "tablesorter-childRow",
    widgets: ["filter", "stickyHeaders"],
    headers: { 4: { sorter: false, filter: false } },
    widgetOptions: {
      filter_cssFilter: "tablesorter-filter",
      filter_ignoreCase: true,
      filter_columnFilters: true,
      filter_saveFilters: true,
      filter_reset: ".reset",
      filter_startsWith: false,
      filter_childRows: true,
      filter_childByColumn: true,
      filter_childWithSibs: false,
      stickyHeaders: "",
      stickyHeaders_offset: 200,
      stickyHeaders_cloneId: "-sticky",
      stickyHeaders_addResizeEvent: true,
      stickyHeaders_includeCaption: true,
      stickyHeaders_zIndex: 2,
      stickyHeaders_attachTo: null,
      stickyHeaders_xScroll: null,
      stickyHeaders_yScroll: null,
      stickyHeaders_filteredToTop: true
    }
  })
  .tablesorterPager({
    // target the pager markup - see the HTML block below
    container: $pager,
    size: 10
  });
```

Is there suggestion to improve the performance in IE ?

<sub>_(Herst: Fixed formatting.)_</sup>

**Comment by Mottie** [comment]
Hi @thayanithi!

If only IE11 is slow, I think you might be better off setting the [`delayInit` option](https://mottie.github.io/tablesorter/docs/#delayinit) to `true`... this delays processing the cache until after the user sorts or filters the table.

One additional thing that might help is setting the pager [`removeRows` option](https://mottie.github.io/tablesorter/docs/#pager-removerows) to `true`. This will remove, instead of hiding, rows that aren't visible during paging.

And if that doesn't help, you might want to try out [DataTables](https://github.com/DataTables/DataTables/)... Once I get started on the rewrite of tablesorter, I'll work on optimizing performance and hopefully this won't be an issue anymore.

**Comment by thayanithi** [comment]
Performance increased Significantly . Thanks a Lot.

Another one issue I am adding child row through Ajax call after that updating the table using ("#table_id").trigger("update") to align child row with parent while search.

Trigger updated takes 4 sec to rebuild entire table, Is there any way to reduce the rebuild time

**Comment by Mottie** [comment]
I'm not exactly sure what you mean by "align child row with parent while search"...

If you are adding rows, you *should* be able to use the [`addRow` method](https://mottie.github.io/tablesorter/docs/#addrows). I say "should" because I'd have to double check to ensure that the method works properly when adding a child row.

**Comment by thayanithi** [comment]
If I use '$("#table").trigger( 'addRows', [ $row, resort ] )' will it rebuild table. I do not want to rebuild the table entire table.

**Comment by Mottie** [comment]
The `addRow` method will only update the cache with the new row. It doesn't rebuild the cache. Please make sure that the `$row` parameter only contains the newly added row - it should already be appended to the table when this method is called.

**Comment by thayanithi** [comment]
Thanks Mottie working but there is an other issue. After adding row when click sort newly added rows are moved to bottom of the table  I am adding Row in middle of the table.

**Comment by Mottie** [comment]
It sounds like the cache isn't being updated... are you using "update" or "addRow" after adding the row?

**Comment by thayanithi** [comment]
Add Row

**Comment by Mottie** [comment]
The `addRow` method only adds the rows you provide it into the cache.... so unless you're adding 2000 rows, it shouldn't have any performance issues.

**Comment by thayanithi** [comment]
addRow is not an issue when I add row to table adding as expected. sorting is the issue when i click sort icon newly added row present in the bottom of the table.

**Comment by Mottie** [comment]
Hmm, I'm not sure why `addRows` isn't working for you... I [know it works](https://mottie.github.io/tablesorter/docs/example-add-rows.html).

Are you still using the pager? The [`removeRows` option](https://mottie.github.io/tablesorter/docs/#pager-removerows) is a pager option and should be added to either the pager function call:

```js
$table.tablesorterPager({
  // target the pager markup - see the HTML block below
  container: $pager,
  size: 10,
  removeRows: true
});
```

Or, if you're using the widget, add it to the `widgetOptions` as `pager_removeRows`:

```js
$table.tablesorter({
  // ...
  widgetOptions: {
    pager_removeRows: true,
    pager_selectors: {
      container: $pager
    },
    pager_size: 10,
    // ...
  }
});
```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
