### ISSUE TITLE
Chaining tablesorter and tablesorterPager function calls gives TypeError.

### ISSUE THREAD

**Issue by Miega** [Mottie/tablesorter#1435]
I'm attempting to chain multiple function calls in my script, but I keep getting `Uncaught TypeError: $(...).tablesorter(...).tablesorterPager is not a function` whenever I try to get it on my webpage.

[I posted a question on Stack Overflow about this, but none of the answers have been satisfactory.](https://stackoverflow.com/questions/45289832/jquery-chaining-multiple-functions-gives-uncaught-typeerror)

**Comment by Mottie** [comment]
Hi @Miega!

The chaining should work - as it is in [this demo](https://mottie.github.io/tablesorter/docs/example-pager.html). Please make sure:

* jQuery is loaded first, then tablesorter, then the pager.
* Make sure you're using compatible versions of the tablesorter plugin and pager - I recommend using the most up-to-date versions.
* Call the `InitializeTableSorter()` function either at the bottom of the page or inside of a document ready function.
* Are you using jQuery and not jQuery slim or Zepto? I actually don't know if slim will cause an issues since I haven't tested it, but it would be useful information to know.

If none of the above solves the issue, then please share the code that calls the `InitializeTableSorter()` function.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
