### ISSUE TITLE
sortInitialOrder is ignored when going from multi-column sort to single-column sort

### ISSUE THREAD

**Issue by DakuTree** [Mottie/tablesorter#1445]
Pretty much as the title says, sortInitialOrder seems be ignored when doing a single-column sort of a column currently in a multi-sort.  

Example code ([JSFiddle](http://jsfiddle.net/eY8uH/1889/)):
```
$(".tablesorter").tablesorter({
	sortList: [[0, 'a'], [1, 'a']],
	headers: {
		1: {
			sortInitialOrder: "asc"
		}
	}
});
```
Clicking the second column here should change ```[[0, 'a'], [1, 'a']]``` to ```[[1, 'a']]```, but instead we get ```[[1, 'd']]```.  
Unsure if this intentional or a bug.

**Comment by Mottie** [comment]
Hi @DakuTree!

That is the expected behavior since the column already has a sort applied (i.e. a pseudo first-click has already been used). Clicking on the column will increment an internal counter to use the next sort.

That being said, you can add the following undocumented method inside the `initialized` callback to override the internal counter ([demo](http://jsfiddle.net/eY8uH/1890/)):

```js
$(function() {
  'use strict';
  $(".tablesorter").tablesorter({
    sortList: [[0, 'a'], [1, 'a']],
    headers: {
      1: {
        sortInitialOrder: "asc"
      }
    },
    initialized: function(table) {
    	var sortVars = table.config.sortVars;
      sortVars.forEach(function(el) {
      	// reset the internal counter
        el.count = -1;
      });
    }
  });
});
```

**Comment by Mottie** [comment]
Whoops, it is documented <img title=":_happy:" src="https://cloud.githubusercontent.com/assets/136959/13559407/7996bb94-e3d9-11e5-9b36-a39832cd3ceb.gif"> 

See [`config.sortVars`](https://mottie.github.io/tablesorter/docs/#variable-sort-vars).

**Comment by DakuTree** [comment]
Works well. Thanks for the quick help! :+1:
