### ISSUE TITLE
Can't update bower package

### ISSUE THREAD

**Issue by auchri** [Mottie/tablesorter#1448]
I've installed the v2.28.9 bower package in visual studio. Now I tried to update to the latest version available (v2.28.15), but it seems that bower is looking at the wrong repo and can't find the correct tag.

```
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Web\External;%PATH%;C:\Program Files\Git\bin
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Web\External\Bower.cmd" install tablesorter#v2.28.15 --force-latest --save
bower tablesorter#v2.28.15  not-cached https://github.com/christianbach/tablesorter.git#v2.28.15
bower tablesorter#v2.28.15     resolve https://github.com/christianbach/tablesorter.git#v2.28.15
bower tablesorter#v2.28.15     ENORESTARGET No tag found that was able to satisfy v2.28.15
Additional error details:
No versions found in https://github.com/christianbach/tablesorter.git
```

**Comment by Mottie** [comment]
Hi @auchri!

This is the only commit (https://github.com/Mottie/tablesorter/commit/1dce1bc2df241e7975d234f1db24a24653ab246e#diff-0a08a7565aba4405282251491979bb6b) made to the `bower.json` since v2.28.9.

I'm not sure why visual studio is looking in the wrong repo... maybe the [suggestion from here](https://github.com/aspnet/Tooling/issues/575#issuecomment-277696647) will help? I know the solution is targeting fixing version numbers and not repo locations, but it's a start and sounds similar.

**Comment by Mottie** [comment]
Hmm, I'm not sure why I didn't notice before, but the update output shared above is targeting the wrong repo. Anyway, I'm guessing this isn't any issue any more, so I'm closing it.
