### ISSUE TITLE
Replace disabled filter textbox with a button / editable cell select list

### ISSUE THREAD

**Issue by rwilkin** [Mottie/tablesorter#1498]
Hi,
I have two things I'm trying to do. I've been searching for a while now and haven't found anything. 
What I have is a table with with the filter and editable widgets enabled. 

First thing I'm trying to do:
Column 0 in my table is disabled in the filter so it puts a disabled text box there. 
What I want to do is replace that disabled textbox with a button that when you click the button it resets the filter. 

The second thing I'm trying to do is with the editable cells. I want to make one column of cells have a select box instead of a text box. 

Is that something that is possible at the moment? If not can I request it as a feature?

Thanks in advance for any help

**Comment by Mottie** [comment]
Hi @rwilkin!

The things you requested aren't built into tablesorter, but you can add them:

1. In the code below, the `replaceFilter` function hides the existing input and adds a reset button. It is called when the `filterInit` event is fired.
2. To add a select, you'll need the `setVal` and `addSelect` functions. They are called by using a delegated event binding on the table. The table cell is updated after the selection is made, or you can press <kbd>Esc</kbd> (twice, since the first time cancels the select and the second cancels the change) to revert the value.

Note: I am assuming the above two methods are applied to the same column. If not, change one of the two `' + column + '` within the appropriate function to the desired column.

Here is a ([demo](https://jsfiddle.net/Mottie/8crx66yk/)):

```js
$(function() {

  var $table = $('table'),
  options = ['abc 1', 'abc 2', 'abc 3'],
  column = 1; /* one-based index */

  function replaceFilter() {
    var $cell = $table.find('.tablesorter-filter-row td:nth-child(' + column + ')');
    $cell.find('input').hide();
    $('<button type="button">Reset</button>')
      .appendTo($cell)
      .click(function() {
        $table.trigger('filterReset');
      });
  }

  function setVal($cell, value) {
    $cell.text(value);
    $table.trigger('updateCell', $cell);
  }

  function addSelect($cell) {
    var originalValue = $cell.text();
    $cell.text('');
    $('<select>')
      .append('<option>' + options.join('</option><option>') + '</option>')
      .val(originalValue)
      .appendTo($cell)
      .one('keydown', function(event) {
        if (event.which === 27) {
          setVal($cell, originalValue);
        }
      })
      .one('change', function() {
        setVal($cell, $(this).val());
      });
  }

  $table
    .on('filterInit', replaceFilter)
    .on('click', 'td:nth-child(' + column + ')', function() {
      var $cell = $(this);
      if (!$cell.find('select').length) {
        addSelect($(this));
      }
    })
    .tablesorter({
      theme: 'blue',
      widgets: ['zebra', 'filter']
    });
});
```

**Comment by rwilkin** [comment]
Hi Mottie,

Thank you for your fast reply. This works beautifully. 
I noted that if the editable widget is loaded with this the select boxes do some strange things. After removing the editable widget it worked like a charm. I added another function to add text boxes and verification of the inputted data and all is good.

Thank you very much for your help and keep up the awesome work, it is very much appreciated.
