### ISSUE TITLE
How to sort Date in format 10/01/13

### ISSUE THREAD

**Issue by webmatrix** [Mottie/tablesorter#150]
Hello,

I am unable to sort date with format dd/mm/yy .

I tried option in dateFormat: "ddmmyy"  in tablesorter .But it is not sorting.

Regards,
Abhijit

**Comment by bcmatz** [comment]
I have tried every example above and more and for the life of me cannot seem to get a column with a two digit year and a time to sort correctly.  In debug mode, the console tells me that the column sorter is text, however when I change that column data to use 4 digit year, it is shortDate.

Please advise.

**Comment by Mottie** [comment]
Hi @bcmatz!

Did you include the two-digit year parser from above? Also, since it is not set up to auto detect the two-digit year, you'll need to assign it to a column. If you are using my branch of tablesorter, then add a `"sorter-ddmmyy"` class name to the header.

If you need a different two-digit year format, then include the [`parser-date-two-digit-year.js` file](https://github.com/Mottie/tablesorter/blob/master/js/parsers/parser-date-two-digit-year.js) instead.

**Comment by bcmatz** [comment]
Yes.  My code is as follows:

$.tablesorter.addParser({
                    id: "ddmmyy",
                    is: function(s) {
                        return false;
                    },
                    format: function(s, table, cell, cellIndex) {
                        s = s
                            // replace separators
                            .replace(/\s+/g," ").replace(/[\-|\.|\,]/g, "/")
                            // reformat dd/mm/yy to mm/dd/yy
                            .replace(/(\d{1,2})[\/\s](\d{1,2})[\/\s](\d{2})/, "$2/$1/$3");
                        var d = new Date(s), y = d.getFullYear();
                        // if date > 50 years old, add 100 years
                        // this will work when people start using "70" and mean "2070"
                        if (new Date().getFullYear() - y > 50) {
                            d.setFullYear( y + 100 );
                        }
                        return d.getTime();
                    },
                    type: "numeric"
                });

jQuery('#reportsTable').tablesorter({
                        debug:true,
                        textSorter: $.tablesorter.sortNatural,
                        widgets: [ 'zebra', 'resizable', 'stickyHeaders', 'columns' ],
                        widgetOptions: {
                            resizable: true
                        }
                    });

and the data in the column of question is like the following (after sort):

01/24/15 23:13 
01/26/15 00:00
01/27/15 22:19
02/06/14 13:55 
03/04/15 14:57

**Comment by bcmatz** [comment]
Also that column header's class is "sorter-ddmmyy"

**Comment by Mottie** [comment]
Then you need to use a different parser... it looks like you need "mmddyy", right? The parser above is for European date formats "dd-mm-yy".

**Comment by bcmatz** [comment]
I didn't even pay enough attention to notice that the parser was not in the format my data expects!  Where can I find a parser for MMDDYY offhand ?

**Comment by Mottie** [comment]
I linked to the file above.

**Comment by bcmatz** [comment]
Are you referencing parser-date-two-digit-year.js ?

**Comment by bcmatz** [comment]
included the file parser-date-two-digit-year.js and still does not sort column correctly.

**Comment by Mottie** [comment]
Are you adding a header class name of `"sorter-mmddyy"`?

**Comment by bcmatz** [comment]
Yes

**Comment by Mottie** [comment]
It works for me: http://jsfiddle.net/Mottie/abkNM/6525/

It doesn't look like you changed the [`usNumberFormat` option](http://mottie.github.io/tablesorter/docs/#usnumberformat) (default is `true`), but make sure it's `true`... I'm making sure, just-in-case.

**Comment by bcmatz** [comment]
Examining your example, sorting by the only column, I get:


Date
01/24/15 23:13
01/26/15 00:00
01/27/15 22:19
02/06/14 13:55
03/04/15 14:57
06/2/15 10:22
11/1/12 8:14 AM

Which is not sorted by date correctly (notice 02/06/14 between two 2015 dates)

The problem seems to be sorting on the full date, including year.  Year does not seem to be taken into account

**Comment by Mottie** [comment]
Sorry, I posted 6525 originally without the "sorter-mmddyy" as a header class name... I updated the link almost immediately to http://jsfiddle.net/Mottie/abkNM/6526/ but that doesn't update any emails that were send out... Try the updated demo instead.

**Comment by bcmatz** [comment]
AHA, I believe I have figured out the issue.  In my table, in the <THEAD> section, there is a <TR> which houses all column headers, and an additional <TR> which contains count/average info for each column.

I believe the issue is that when that extra ROW in the THEAD element is present it skews the sort algorithm.

Example:

<thead>
<tr>
<th class="sort-mmddyy">some header></th>
<th>header 2></th>
<th> header 3></th>
<th>header 4></th>
</tr>
<tr>
<td>some additional stuff</td>
<td>some additional stuff</td>
<td>some additional stuff</td>
<td>some additional stuff</td>
</tr>
</thead>

Could this be the issue ?

**Comment by Mottie** [comment]
Ah, yeah, it's probably because of the second row.

Tablesorter assumes that the last cell for a column contains the class name, so you can either move the class name to the last row, unless you plan to add `colspan` or `rowspan`.

Alternatively, you can get tablesorter to ignore the second column by adding this class name:

```html
<tr class="tablesorter-ignoreRow">
  <td>some additional stuff</td>
  <td>some additional stuff</td>
  <td>some additional stuff</td>
  <td>some additional stuff</td>
</tr>
```

**Comment by bcmatz** [comment]
That was EXACTLY the solution I needed!  Thanks!

I wonder if it makes sense to modify tablesorter in such a way that it only sorts based upon the data within the ```<TBODY>``` tag?

**Comment by Mottie** [comment]
Huh? What do you mean by that?

It would make this conversation much easier if you would jump on to the `#tablesorter` IRC channel on freenode.net... [irccloud.com](https://www.irccloud.com/) makes it easy if you don't have a chat program.

**Comment by bcmatz** [comment]
i'll hop in there in a little bit!
