### ISSUE TITLE
Unable to get nested table to show the Sticky Header

### ISSUE THREAD

**Issue by JesperGJensen** [Mottie/tablesorter#1512]
I have a Table with nested tables containing details.
I am unable to get the nested table to show the Sticky Header.
I can confirm with inspect, that the sticky headers are generated, they are just hidden permanently.

JSFiddle Example.
http://jsfiddle.net/JesperGJensen/dczpvkad/7/

I have been trying to follow the example from https://mottie.github.io/tablesorter/docs/example-widget-sticky-header.html

**Comment by Mottie** [comment]
Hi @JesperGJensen!

I think it's not working because of nested sticky header is not being appended to the `.body`. Once I did that it sorta started working, but it's still broken. I didn't account for a use-case where nested sticky headers were used inside of a scrollable element. Give me some time to work on this and find a solution.

**Comment by Mottie** [comment]
Fixed in v2.29.6.
