### ISSUE TITLE
filter-select no longer exact match?

### ISSUE THREAD

**Issue by mtgtnt** [Mottie/tablesorter#1556]
I have had to add:
`					filter_excludeFilter: {
						0: 'range',
						1: 'range',
						2: 'range',
						3: 'range',
						4: 'range',
						5: 'range',
						6: 'range',
						7: 'range',
						8: 'range',
						9: 'range'
					},
`today to deal with the "space dash space" thinking there is a range filter set. I do not recall this happening before after you set it to be exact match many many versions ago.

**Comment by Mottie** [comment]
Hi @mtgtnt!

There were some adjustments made to the select behavior [last year](https://github.com/Mottie/tablesorter/commit/7385ed4bf1bb5c719aaa4a10c4b43783f5a755ac) (in v2.28.12) to get the filter to properly work with [jQuery UI selectmenu](https://jqueryui.com/selectmenu/).

You don't need to target every column. The `filter_excludeFilter` can target the header class name as well:

```js
$(function() {
  $("table").tablesorter({
    widgets: ["filter"],
    widgetOptions: {
      filter_excludeFilter: {
        ".tablesorter-header": "range"
      }
    }
  });
});
```

Related to [issue #1520](https://github.com/Mottie/tablesorter/issues/1520#issuecomment-370782677)... I can look at the code again and see if I can fix it to use the "exact" filter type directly instead of only using it when a user includes an "or" or "and" in the query.

**Comment by mtgtnt** [comment]
Thanks for the '.tablesorter-header': 'range' tip. For now this works fine, just caught me off guard. Was using a previous version where it was working so I didnt think anything about it till a user informed me something was a miss when using the filters. Took a bit to figure out it was the dash (range).

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
