### ISSUE TITLE
Issue with colspan in cells, breaking sorting randomly

### ISSUE THREAD

**Issue by 0xpr03** [Mottie/tablesorter#1577]
I'm trying to sort a multi-header table that includes colspan cells.
It works most of the time but breaks at some cases, specifically a mix of colspan + font awesome columns that use a data-text break sorting entirely, at least most of the time...
I'm a bit confused and would appreciate help.
Failing jsfiddle:
https://jsfiddle.net/2zhjsn31/12/  
Fails for `Flags` on `2018-06-10` as well as `2018-06-24` but works for other parts.
If you remove the first row entry (3110901) it will work at least for `2018-06-24` again: https://jsfiddle.net/2zhjsn31/13/

To add some code and not only links: `<td colspan=3></td>` is creating Problems together with `<td class="success" data-text="afk"><i class="fas fa-clock" title="AFK"></i></td>`
Debugging enabled shows that at some points columns are detected as digit and in the next week as text, so I'm not sure if that plays also a part.

I'm not using any widgets for this and didn't find any difference to your colspan demo. I've searched for related issues here, in the Docs and the FAQ. I also tried to get help on IRC & Stackoverflow first.

**Comment by Mottie** [comment]
Hi @0xpr03!

It looks like the parser for the "Flags" column is being set to "digit". This is likely due to all the `colspan`s.

If you add a `class="sorter-text"` to each Flags column ([demo](https://jsfiddle.net/Mottie/2zhjsn31/15/)):

```html
<th class="sorter-text">Flags</th>
```

or, add the following [`headers` option](https://mottie.github.io/tablesorter/docs/#headers); I know the nth-child selector is confusing, but it targets the "Flag" column ([demo](https://jsfiddle.net/Mottie/2zhjsn31/16/)):

```js
	headers: {
  	':nth-child(3n+2)': { sorter: 'text' }
  },
```

**Comment by 0xpr03** [comment]
Thanks @Mottie !
I'm a little bit confused about the bugfix, but I'm now using the `th` class approach when generating the table.
(Dynamically created via ajax on the client.)

The `nth-child` fix seems to me like the smarter but also more confusing fix.

**Comment by Mottie** [comment]
It's really hard to figure out which parser to use when there are colspans all over the place. The code that decides which parser to use doesn't really deal with colspans properly because we could need to "properly" index each row & cell (add a `data-column="x"`) and that takes a lot of time.

The most reliable and easiest solution would be to add a `sorter-{parserName}` class name to each header cell:

```html
<tr>
  <th class="sorter-digit">ID / USN</th>
  <th class="sorter-text">Flags</th>
  <th class="sorter-digit">EXP</th>
  <th class="sorter-digit">CP</th>
  ...
  <th class="sorter-text">Flags</th>
  <th class="sorter-digit">EXP</th>
  <th class="sorter-digit">CP</th>
</tr>
```

Or, associate already established header class names with the parser in the `headers` option:

```html
<tr>
  <th>ID / USN</th>
  <th class="flags">Flags</th>
  <th>EXP</th>
  <th>CP</th>
  ...
  <th class="flags">Flags</th>
  <th>EXP</th>
  <th>CP</th>
</tr>
```

```js
headers: {
  '.flags': { sorter: 'text' }
}
```

**Comment by 0xpr03** [comment]
I guess depending on the first row and whether it had a colspan some Flag columns got set to digit, erasing their real value.
I'm now using the th approach at all headers in the original Table. The biggest problem was figuring out what really happened and stripping down the original, dynamically generated table (before the font awesome JS kicks in, which could also change stuff)

**Comment by 0xpr03** [comment]
The problem was that the culprit row was changing depending on the selected date range to display. So it looked like depending on the selected data some flag sorting just randomly failed, while in reality the first row just so happened to include a colspan at that exact week.

**Comment by 0xpr03** [comment]
Last comment: I just realized this can save me some headaches with a "nickname" column I have, where potentially I'll have a digit-only name as first entry at some point.
