### ISSUE TITLE
Filter on an input in a table

### ISSUE THREAD

**Issue by FlorianChretien** [Mottie/tablesorter#1639]
Hello,

Since one or more update we can not use the filter of the columns of a table if there is an input .. Is this normal? Thank you

**Comment by Mottie** [comment]
Hi @FlorianChretien!

I haven't noticed this behavior. I set up [this demo](https://jsfiddle.net/Mottie/bbxxomhx/1968/) that uses [`parser-input-select.js`](https://github.com/Mottie/tablesorter/blob/master/js/parsers/parser-input-select.js) to get the input values from the column, if an input exists. Notice that when a cell contains both text and an input, only the input value is parsed and becomes filterable. This is because of how the parser is set up.

I don't know the particular situation you have set up to encounter the described problem, so please update that demo. Then I should be able to help find a solution.

**Comment by FlorianChretien** [comment]
A forgotten import! Sorry
Thank you
