### ISSUE TITLE
Resizing columns when sticky headers are active.

### ISSUE THREAD

**Issue by naska47** [Mottie/tablesorter#335]
I'm unable to resize the table columns while a sticky header is visible on that table.  It would be nice to be able to have sticky headers active all the time and still be able to resize the columns.

**Comment by Mottie** [comment]
Ok, so I finally got around to fixing this... I had to rewrite a big chunk of the resizable widget!

I forgot there was an open issue, but I did remember it! The fix is here: https://github.com/Mottie/tablesorter/commit/673d7cbbb517c7c7e849aa7288776ea915e8cbd9

And the [resizable demo](http://mottie.github.io/tablesorter/docs/example-widget-resizable.html) now includes stickyHeaders so I know it works ;)
