### ISSUE TITLE
How to refresh Ajax pager widget after adding or removing rows ?

### ISSUE THREAD

**Issue by Prestaplugins** [Mottie/tablesorter#455]
Hello,

When there's more than 1 page, after adding or deleting rows through Ajax, I do : 
$('.tablesorter').trigger('update', [true]);
$('.tablesorter').trigger('refreshWidgets', true, false);
Everything is refreshing.

Now, if I have only 1 page of records and I try to remove or add a row (even a row that should create a 2nd page) pager and table are not refreshed.

How to correctly refresh my table whatever the number of page ?
Thanks a lot in advance.

**Comment by lurajon** [comment]
Hi!
I have a similar problem. I am using version 2.17.2 with the ajax pagination. The user has the option to delete rows in the table. The total count and everything updates, but not to the correct value.

If I have 200 rows in total of a filtered dataset and I only show 20 rows and then delete 2.
The t.trigger('update') updates the table. The paginator infromation is however not updated correctly. It will for instance only show 18 rows, and the pager information shows 1-18 of 18, and the next, prev buttons are disabled. It should display 1-20 of 118. 

Is it possible to trigger a update that executes an ajax call with the ajaxProcessing etc manually after a row is deleted?

Best regards, 

Jone

**Comment by Mottie** [comment]
Hi @lurajon!

Try using the [`pageSet` method](http://mottie.github.io/tablesorter/docs/#pageset). It will need the current page included, I think, because it would otherwise reset to page 1.

If that doesn't work, I would recommend updating tablesorter to the latest version as there is now a [`pagerUpdate` method](http://mottie.github.io/tablesorter/docs/#pagerupdate) which could be used.

**Comment by lurajon** [comment]
Thanks @Mottie !

I upgraded to the latest version and used the pagerUpdate method.

Best regards,

Jone
