### ISSUE TITLE
Hide Entire Column But Still Filter Table

### ISSUE THREAD

**Issue by avoorhees** [Mottie/tablesorter#477]
First of all, love the plugin. 

I have a use case where I want to hide the entire column (header,input,background of input, and row) but still need to be able to filter the table on this column. I use external buttons to filter instead of having the user type in input box. 

```
table.tablesorter thead tr.tablesorter-filter-row input.disabled { 
    opacity: 0.5; 
    filter: alpha(opacity=50); 
}
```

The issue with this code is that the filter must be disabled, but I need the filter to still work, just the entire column hidden.

Thanks in advance!

**Comment by yudicrownit** [comment]
Hello i am using tablesorter with few more functionalities.

I am using jquery ui sorting to sort the rows and updating the serial number on sorting now the issue came to me is when i click on some button i want to hide specific rows from tablesorter but if i do this with css display none it broke when i change the page all the rows are visible now also if i use css display none the rows on first pager should be 10 but after hiding 2 rows there are only 8 rows on 1st pager. 

Could you please help me how to hide the rows permanently and work on other rows i can give a hidden class to them

**Comment by Mottie** [comment]
Hi @yudicrownit!

That is interesting. So you want to keep the column sort and still be able to manually sort rows?

When hiding the selected rows, add a class name of `"tablesorter-filter"` instead of setting the css display. The pager looks for that class name instead of using jQuery's much slower `:visible` method when determining which rows to include in a page.

**Comment by yudicrownit** [comment]
Well i did it...what i did is i just removed the inactive rows from the actual position to append to the last position in table with display:none!important and when use disable the toggle button inactive comes back to actual position...and for that bug where it was showing only 8 rows i am destroying the tablesorter and calling it again..now its working just perfect!

**Comment by pauldube** [comment]
Hi Mottie,

I implemented the solution you gave to avoorhees. However my implementation is using a checkbox to display rows when the value 1 is in the hidden column or show all if empty. So the checkbox sets the value 1 in the hidden field and triggers the search (or clear the value in the hidden field and triggers the search). This works fine except that the search fields become visible on all fields. Is it possible to keep them hidden unless there is a search term entered as would be expected?

**Comment by Mottie** [comment]
Hi @pauldube!

If you don't want to add a filter row, set the [`filter_columnFilters` option](https://mottie.github.io/tablesorter/docs/#widget-filter-columnfilters) to `false`. Or am misunderstanding the question?

**Comment by pauldube** [comment]
I like the filter row to hide when not necessary. Take a look at [this demo](http://jsfiddle.net/qqngd49u/1). I want the filter row to disappear normally when checkbox is checked (if there is no text entered in any filters of course).

**Comment by Mottie** [comment]
Ah ok, I'll see what I can come up with to accomplish that request.

**Comment by Mottie** [comment]
Ok @pauldube! I've updated the `filter_hideFilters` setting to now accept a function. It's currently only available in the master branch. I've also updated the documentation, but you won't be able to see it until the next release; which should be soon.

You can use it as follows ([demo](http://jsfiddle.net/Mottie/qqngd49u/2/))

```js
filter_hideFilters: function(config) {
  // get an array of filter queries
  var search = $.tablesorter.getFilters(config.$table);
  // ignore any query is column 2 (zero-based index)
  search.splice(2, 1);
  // return true to hide the filter row, false to show it
  return search.join("") === "";
}
```

The demo is using the `widget-filter.js` from the master branch. It is also loading `widget-storage.js` separately as the `jquery.tablesorter.widgets.js` file won't get updated until the next release.

**Comment by pauldube** [comment]
Ohhh! It works great. You're the best!
