### ISSUE TITLE
Scroller widget with browser zoom

### ISSUE THREAD

**Issue by drlovegrove** [Mottie/tablesorter#680]
Hi,

I'm having a problem with the scroller widget when using the browser's zoom-in/out feature. At 100% everything is fine, but at other zoom levels, the columns in the header dont always match up with the columns in the main table. 

My problematic table has about 40 columns, so the problem is quite exaggerated, but you can actually see it going wrong on the main scroller page if you zoom in a bit:
http://mottie.github.io/tablesorter/docs/example-widget-scroller.html

It seems worst in chrome, but goes wrong on all the browsers i've tried. 

I dont think it's linked to theme as I'm using bootstrap, and the docs example goes wrong with jqueryui.

Any ideas ? 

Thanks,

**Comment by Mottie** [comment]
@bernier & @drlovegrove Please test out the scroller widget updates. In order to make it work properly, you'll need to update the following from the working branch:

* [widget-scroller.js](https://github.com/Mottie/tablesorter/blob/working/js/widgets/widget-scroller.js)
* [jquery.tablesorter.js](https://github.com/Mottie/tablesorter/blob/working/js/jquery.tablesorter.js)
* [jquery.tablesorter.widgets.js](https://github.com/Mottie/tablesorter/blob/working/js/jquery.tablesorter.widgets.js)

I plan on pushing the working updates to the main branch soon.
