### ISSUE TITLE
Extremely slow perfomance with large dynamic tables

### ISSUE THREAD

**Issue by SergeyKiriyenko** [Mottie/tablesorter#770]
I am currently trying to implement Filter Widget External Search with Tablesorter into dynamic tables. However, with small tables (up to 10K rows) everything works fine. But with large datas (more than 10K rows) everything stucks and the page doesn't respond. Is there any way to somehow optimize the performance and make the filter widget work with more than 10K rows. I'm using TableSorter (FORK) 2.18.3, tablesorter (FORK) pager plugin updated 11/3/2014 (v2.18.2) and tableSorter (FORK) 2.16+ widgets - updated 11/7/2014 (v2.18.3).

**Comment by sennz** [comment]
Hi
I have a table with 20 col and around 8000 rows, it takes long time to load, filter or sort. How can i improve the performance. Also How can I show a progress bar or a overlay so that user get noticed that the table is not ready.
Thanks in advance.

**Comment by Francks11** [comment]
Hello @sennz,

tablesorter is not optimize for huge table data for now...

The solution is to implement virtual scrollbar and add in DOM only visible table row... Which this technic, we can have table with millions rows...

But this isn't implemented yet...

Mottie said in issue https://github.com/Mottie/tablesorter/issues/933, that he is looking about Clusterize.js http://nexts.github.io/Clusterize.js/.

How works Clusterize ?

The main idea is not to pollute DOM with all used tags. Instead of that - it splits the list to clusters, then shows elements for current scroll position and adds extra rows to top and bottom of the list to emulate full height of table so that browser shows scrollbar as for full list

@Mottie, It is for when the implementation of Clusterize? :-p

Thanks
