### ISSUE TITLE
Remove hidden rows from tablesorter

### ISSUE THREAD

**Issue by kezz** [Mottie/tablesorter#779]
In my table a number of rows need to be hidden upon start-up. Then, during the user browsing the table, some rows will need to be removed and some of the hidden rows will need to be unhidden. Some of the rows that are removed will need to be put back again later.

I have tried giving all of the rows that need to be hidden `display: none`, `visibility: hidden` and `display: collapse` but none work.

Is this possible using tablesorter?

**Comment by Kezz101** [comment]
Hi there!

Sorry to be such a pain but it seems to have broken and I'm not sure what the problem is. I've been staring at this code for hours trying to fix it to no luck. The child rows are still working correctly and staying underneath their parents but the hiding and showing of rows isn't working again. However, oddly enough it is working for the info row.

Could you perhaps help me? I've updated the [Pastebin](http://pastebin.com/wKqYeE2Y) link with some bits of the code that have changed.

Thanks,
Kieran

**Comment by Mottie** [comment]
Hi @Kezz101!

It looks like the `invisible-table-row` class name is being added and removed. This does break how tablesorter sorts child rows. So I think the easiest solution would be to add an additional class name for child rows; the default setting is `tablesorter-childRow` in addition to the invisible table row class name ([demo](http://jsfiddle.net/Mottie/d2r0Lgav/)).

Don't use the `cssChildRow` option in this case, and remove the triggered update immediately after tablesorter is initialized - it isn't needed.

```js
$(".tablesorter").tablesorter({
    theme: "bootstrap",
    widthFixed: true,
    headerTemplate: "{content} {icon}",
    // cssChildRow: 'invisible-table-row',
    sortList: [[0,0]],
    widgets: ["uitheme", "filter", "zebra"],
    widgetOptions: {
        zebra: ["even", "odd"],
        filter_reset: ".reset"
    }
});

// tablesorter was just initialized; this code is not needed
// $(".tablesorter").trigger("update", false);
```

And make sure that this css is defined somewhere:

```css
.invisible-table-row {
    display: none;
}
```

**Comment by Kezz101** [comment]
Hey @Mottie! 

I've updated the code as you said and now the child row is correctly appearing and disappearing which is great. However, the parent row isn't disappearing at all. I've updated my [Pastebin](http://pastebin.com/wKqYeE2Y) with the new code and I would be very grateful if you could take a look at it and see what the error is.

Thanks for all your help!

**Comment by Mottie** [comment]
It's working fine for me. I used the filters - permission group selector & typed in "b" in the email, then the name column - and everything appears to work perfectly.

Or, is there a different reason for the parent row to disappear that I'm missing? The pager isn't being used. Looking at the delete button code, I am not familiar with the `confirmation` function plugin, but whatever it is see if it has an option to bind to a [delegated event](http://api.jquery.com/on/#direct-and-delegated-events) because the rows within the table are refreshed each time you sort.

The other buttons are working because of the `onclick` function assignments on the button.

**Comment by Mottie** [comment]
Hmm, well when the filters are applied, it adds a `display: table-row` style to the row which is overriding the css style. I know it's not encouraged, but I think in this case you might need to use an `!important` flag.

```css
.invisible-table-row {
    display: none !important;
}
```

As for the pager not working, there are only 3 rows in [this demo](), so it doesn't look like it's working, but it is. I did find a bug causing the page count to be off if the first tbody isn't being targetted by the pager (info-only tbody) which I just fixed in the working branch (https://github.com/Mottie/tablesorter/commit/638d070f3ad3c1ead30c060a7fb5a440546f994e). Please use the updated [pager file](https://github.com/Mottie/tablesorter/blob/working/addons/pager/jquery.tablesorter.pager.js).

**Comment by Kezz101** [comment]
Thanks for the help! `!important` seems to do the trick. I'll put the pager back in and double check everything's working.

**Comment by Kezz101** [comment]
Brilliant the pager works a treat too! Thank you for all the help :smile: 

Sorry to be a pain but I also seem to be having trouble getting the print widget to work. The idea is that the infoOnly row, the child rows and the all the columns with the buttons in will be removed in the `print_callback` function and then this will be printed. However, when I press the print button nothing happens at all. 

I've updated the [Pastebin](http://pastebin.com/wKqYeE2Y) with the new code.

**Comment by Mottie** [comment]
Within the print_callback, the jQuery `find()` method is not being used, try this ([demo](http://jsfiddle.net/Mottie/e3V9V/197/)):

```js
print_callback: function (config, $table, printStyle) {
    $table.find(".tablesorter-infoOnly").remove();
    $table.find(".print-remove, .tablesorter-pager").remove();
    $table.find(".tablesorter-childRow").remove();
    $.tablesorter.printTable.printOutput(config, $table.html(), printStyle);
}
```

\* I also included the `.tablesorter-pager` in stuff that needed to be removed.
