### ISSUE TITLE
filter-onlyAvail behavior

### ISSUE THREAD

**Issue by billmn** [Mottie/tablesorter#788]
I'm trying to use "filter-onlyAvail" class but I have a doubt about the right behavior.

Use this table like example:
http://mottie.github.io/tablesorter/docs/example-widget-filter-custom.html

To replicate:
1- Choose an option from "City" filter ( e.g. "E - H" )
2- Open "Discount" select and you can see available options ( "E - H" -> "17%" )
3- Choose an option from "Discount" filter and reopen this select

Now you can see all discounts and not only those visible.

Is this an issue or the right behavior?

**Comment by TheSin-** [comment]
this was by design, if an option is set all options are available on that option so that you can change it, other wise you couldn't change an option with out reseting then entire table.

For example imaging you have a table with 20 filters.  You set each filter, but at the end you decide you want red instead of green and that is the first filter.  You'd have to reset all 20 filters just to select that one, not to mention filters would then need some sort of weight and what would happen to the filters that have no options once you change the red.  they would have an option that isn't even available.

That being said I can see reasons to have and want both options.  filter-onlyAvail was meant for unfiltered selects.  Maybe we need a filter-onlyAvailFiltered or something.  Somehow I thought there was a way of doing this, I thought this was just the default behaviour.

But to answer this question yes filter-onlyAvail was designed to work this way.

**Comment by TheSin-** [comment]
Just to go over it better, in your process you say pick 17%, if filter-onlyAvail limited after the 17% what if you want'ed to then see 18%, you'd have to blank it, and then select 18%, for ajax type tables or large datasets this could take lots of time to do.  That might be a simpler way to explain it.

**Comment by billmn** [comment]
Perfect, thank you for explanation ... now it's more clear.
Thank you again
