### ISSUE TITLE
Error when number of tbody's td is diff of thead's td (getAttribute of undefined)

### ISSUE THREAD

**Issue by sportok** [Mottie/tablesorter#819]
Hello,

Since upgrade to v2.19.0 and v2.19.1 (before i had v2.17.4) i have a problem with tablesorter.

If number of tbody's "td" is not similar to number of thead's "td", an error occured.
For example, if i want a blank row, i must be write : 
<code>$('#table_applicationCompany tbody').append('\<tr>\<td>\</td>\<td>\</td>\<td>\</td>\<td>\</td>\<td>\</td>\</tr>');</code>
Before this upgrade, next code worked : 
<code>$('#table_applicationCompany tbody').append('\<tr>\</tr>');</code>

It is more problematic when i have a "colspan=3" because it not possible to add the real number of td...

<code>ERROR : "Uncaught TypeError: Cannot read property 'getAttribute' of undefined" (in jquery.tablesorter.widgets.min.js)</code>

Have you a solution ?

Thanks,
SportOk

**Comment by Mottie** [comment]
Hi @sportok!

I would not recommend adding an empty row like that because it is evaluated as a row with all empty cells for sorting, so the [`emptyTo` option](http://mottie.github.io/tablesorter/docs/#emptyto) kicks in and sorts it at the bottom (default setting).

If you want to insert and blank row and keep it in place during sorting, then use the [static row widget](http://mottie.github.io/tablesorter/docs/example-widget-static-row.html).

That being said, that is a problem in the code which I will fix :wink:

**Comment by sportok** [comment]
@Mottie Thank you for the fix ! :)
I'll see if I can set up the static widget but I don't think I can use it everywhere.
