### ISSUE TITLE
Initial Filter don't update the table

### ISSUE THREAD

**Issue by TarekZID** [Mottie/tablesorter#839]
I have a problem with setting an initial filter. I do it, like in this demo: http://jsfiddle.net/Mottie/abkNM/785/
But the problem in the demo is, the inital filter shows me the complete table at the beginning. The filter has only an effect if i also use an another filter. 

Someone has a solution? 

Thanks!

**Comment by Mottie** [comment]
Hi @TarekZID!

I know the initial filters are working because they work in [this demo](http://mottie.github.io/tablesorter/docs/example-widget-filter-custom.html). The "Age" column has "<30" set as an initial filter.

To see how it works follow these steps:

* Set a filter in a different column, and clear or change the age column filter
* Reload the page, and you'll see that the last filter set are remembered; because of the [`filter_saveFilters` option](http://mottie.github.io/tablesorter/docs/index.html#widget-filter-savefilters) is set to `true`.
* Click the \[ Reset Search \] button.
* Now reload the page and the initial "<30" setting should return to the Age column.

Essentially, the initial setting only appears on initial load or if all filters are empty.

If you don't like this behavior then set the `filter_saveFilters` option to `false`. Or, maybe that is behaving inappropriately anyway? How do you feel it should behave? I'm always open to ideas.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.
