### ISSUE TITLE
Filter no longer working with most recent update

### ISSUE THREAD

**Issue by BrendanLouis1223** [Mottie/tablesorter#846]
I could not figure out why my site wasn't using the external filter correctly. I use a previous version of the jquery.tablesorter.widgets,js file and it worked. So I can only assume it's an issue with the newest version of that file.Looking for the error, it properly adds the "filtered" class and the filterEnd event is properly fired. It just never hides the "filtered" rows.

**Comment by TheSin-** [comment]
filtered class needs to be defined in the css to do display: none;  It used to add this on it's own, since the class has never been defined but it started to cause issues for child/parent rows so it was removed.  Just add

```
.filtered {
  display: none;
}
```

to your css and it'll working 100%.

**Comment by Mottie** [comment]
Hi @BrendanLouis1223!

Yeah, I guess I didn't document it very well. I had to remove how the filter was hiding and showing table rows because the grouping widget wasn't able to override the inline "display: table-row". So now the following bit of css is required by the filter widget to work properly:

```css
.tablesorter .filtered {
	display: none;
}
```

It's been in all of the provided themes all along, so if you have a custom theme, just make sure to include the above definition.
