### ISSUE TITLE
Problem with textextractor

### ISSUE THREAD

**Issue by killerpapy** [Mottie/tablesorter#847]
Hi everybody !

I have some problem with textExtractor.
This is line sorted :
```
<tr id="sous-groupe-12639" style="visibility:hidden" role="row">
        <td data-sort-value="local 1z" 4"="" style="display: none; colspan=">local 1z</td>
</tr>
<tr id="12887" class="shared_groups" role="row">
	<td class="moreSpace" width="65%" data-sort-value="mama">
		<input class="groupeIds" type="hidden" value="12887" name="teamIds">
		mama
	</td>
</tr>
<tr id="12639" class="shared_groups" role="row">
	<td class="moreSpace" data-sort-value="local 1">
		<a id="lien-groupe-12639" class="lien-ferme" href="#" onclick="plierDeplier(12639,'team');">
			<img style="float: left; padding-right: 10px; padding-top: 3px;" src="../images/plus.png" alt="plus">
		</a>
		<input class="groupeIds" type="hidden" value="12639" name="teamIds">
		local 1
	</td>
</tr>
<tr id="12928" class="shared_groups" role="row">
	<td class="moreSpace" width="65%" data-sort-value="trans aott new">
		<input class="groupeIds" type="hidden" value="12928" name="teamIds">
		trans aott new
	</td>
</tr>
```
Extraction :
```
jQuery("#groupe").tablesorter( {
				sortList: [[0,0]],
				textExtraction: {
					  1: function (node) {
					    return jQuery(node).attr('data-sort-value');
					  }
					}
			}
		); 
```
Problem with sorted value : 
```
local 1z
mama
local 1
trans aott new
```

In line with value "local 1" there is img with alt="plus" and it break the sort.... 

Any idea ?
Thanks.

**Comment by Mottie** [comment]
Hi @killerpapy!

It appears to work for me - [demo](http://jsfiddle.net/Mottie/856bzzeL/80/)

The HTML is a bit mangled, and I don't know why the "local 1z" row is hidden, but with the provided example, I don't think the `data-sort-value` nor a custom `textExtraction` function  is even necessary ([demo](http://jsfiddle.net/Mottie/856bzzeL/79/)).

If you do need to provide specific data for sorting, you can use the built-in `data-text` attribute (name modifiable using the [`textAttribute` option](http://mottie.github.io/tablesorter/docs/#textattribute)) instead of adding a `textExtraction` function.

Lastly, if you do need to a custom `textExtraction` function for other reasons, then please make sure you are using this fork of tablesorter. The original tablesorter does not support defining that function per column ([ref](http://wowmotty.blogspot.com/2011/06/jquery-tablesorter-missing-docs.html#textExtraction)).

**Comment by killerpapy** [comment]
Hi  @Mottie,

Thanks for your response.
For you it works ... 
Look at mine : 
![test](https://cloud.githubusercontent.com/assets/11554510/6730909/d8185452-ce40-11e4-8617-2c39e074103a.jpg)

The hide line (local 1z) is between grp sync 3 and mama. And when you click the "+" a list appear. 

I have the same result without textExtraction. 

And in my table there is 4 columm. I give you only the sorted one...
I'm steel searching..

**Comment by killerpapy** [comment]
In my case when i set alt="a" in the img. local z is in first line ...
And i use the same code in http://jsfiddle.net there is no problem.
I'm stuck...

**Comment by Mottie** [comment]
Hmm, I wonder, does the first cell in the column have an image? If so, it might be setting that column to use the image parser... try adding a `"sorter-text"` class name to the header cell:

```html
<thead>
  <tr>
    <th class="sorter-text">Foo</th>
  </tr>
</thead>
```

**Comment by killerpapy** [comment]
I tried. Same result.
When i tried here there is no problem. https://jsfiddle.net/yr0oxm84/6/

**Comment by Mottie** [comment]
That HTML has some serious issues... 

* `input` elements should not be added between table rows or cells.
* I have no idea if this cell has a colspan, or... 

        <td data-sort-value="local 1z" 4 "=" " style="display: none; colspan=">

Please try cleaning that up and test again.

**Comment by killerpapy** [comment]
The column as sorter-false to sorted it only on display.
I have clean the html code (it's not the mine) and i have the same issue.
To solve the problem, i set alt="local 1".

Thanks for your help.

**Comment by Mottie** [comment]
Well, I'm still curious... can you type this into the console and see what the parser is set to (set `col` to be the column zero-based index)?

```js
col = 1; $('#groupe')[0].config.parsers[col].id
```

If it says "text" then I'm not sure why the alt value from the image is being extracted.

**Comment by killerpapy** [comment]
result : image !

**Comment by killerpapy** [comment]
If i remove the img in "local 1"  it says "text".
There is any solution to force the column type ? 
An other one : 
```
<thead>
  <tr>
    <th class="sorter-text">Foo</th>
  </tr>
</thead>
```

The funny thing is : http://jsfiddle.net/yr0oxm84/18/ .
On this page $('#groupe')[0].config.parsers[col].id return text.

**Comment by Mottie** [comment]
As I said, that demo has "sorter-false" set... it should be "sorter-text".

Or, you can add a definition to the [`headers` option](http://mottie.github.io/tablesorter/docs/#headers):

```js
jQuery("#groupe").tablesorter({
	sortList: [[0,0]],
	headers: {
		1: { sorter: 'text' }
	}
});
```

There are other ways to set a column parser - see [this demo](http://mottie.github.io/tablesorter/docs/example-parsers-class-name.html) for more information. I didn't include that extra information here to avoid confusion.

The reason the parser is being set to image, is because the automatic parser detector is seeing an image in the first cell of that column. If you don't want the alt information from the image used by the sorter, you'll need to set a different sorter.

**Comment by killerpapy** [comment]
You 've found the problem. Reproduce here : http://jsfiddle.net/yr0oxm84/32/
And if i remove sorter-false, there is no problem i need it.
I want to sort the table at first display and then i need to disable it.

**Comment by Mottie** [comment]
Ok, in your case, I would disable the image parser detector ([demo](http://jsfiddle.net/Mottie/yr0oxm84/33/)):

```js
$(function () {
    $.tablesorter.getParserById('image').is = function(){ return false; };
 
    jQuery("#groupe").tablesorter({
        sortList: [[0, 0]]
    });
});
```

**Comment by killerpapy** [comment]
It's perfect ! You solve my problem !
Thank you for your response! Your product is really quality!

**Comment by Mottie** [comment]
Thanks! I'm glad you got everything working :)
