### ISSUE TITLE
Skipping one row in calculating row-sum and sum concatenation

### ISSUE THREAD

**Issue by 9benm2** [Mottie/tablesorter#873]
Hi,

I'm making a table dynamically with JSON.

I am making two sums in this table:
-I have created a row at the top to calculate the sums of each column (with data-math="col-sum").
-I have created a column that will calculate the sums of each row (with data-math"row-sum").

The strange thing happening can be seen in the screenshot attached.

What happens is that the row sum is skipping the 3rd column (with header <0 days), as you can see in the row for SAP and IBM. I did not do anything special with this column (I didn't put an ignore on it for example).

Then the second issue is that the col-sum is concatenating the values instead of mathematically adding them together. If I search in the table, it will update to the right value (32000) though.

Thanks in advance for your help.
Regards,
Ben

![screenshot_18](https://cloud.githubusercontent.com/assets/7681811/7175173/6bb2082c-e41a-11e4-87e1-682c19e4bfec.png)

**Comment by Mottie** [comment]
Hi @9benm2!

Next time, I would really appreciate it and it would save me tons of time if you would please provide the HTML for the table and javascript used to initialize the table; or just modify one of the [jsFiddle demos](http://jsfiddle.net/856bzzeL/) (there are a bunch more basic playground demos to work from on the [main wiki page](https://github.com/Mottie/tablesorter/wiki#tablesorter-playgrounds)). Thanks!

The first issue looks like it's with the [`math_mask` option](http://mottie.github.io/tablesorter/docs/example-widget-math.html#math_mask). When set to `'#'`, zeros will not show up in the format, instead set this option to `'0'`.

```js
math_mask : '0'
```

The second issue looks like a bug in the code. When it encounters the IBM row, second column and there isn't a defined `data-math="row-sum"` in the cell, the parser was returning an empty string instead of zero. That's why the string was being concatenated. I'll push a fix to the master branch to resolve this issue. Please update your `widget-math.js` file from there :)

Here is a [working demo](http://jsfiddle.net/Mottie/856bzzeL/148/) (using the updated widget-math.js file from the master branch of this repo).

**Comment by 9benm2** [comment]
As a workaroud, I calculated the row totals in the back end in Java. It's working fine now.

I am not familiar with issues in github, as this is the first one I ever reported.

Thanks very much for your feedback. Next time I will provide my code in jsFiddle and try to be more clear :)
