### ISSUE TITLE
Dynamic column size and count with sticky headers

### ISSUE THREAD

**Issue by seratkurtulus** [Mottie/tablesorter#874]
Hello,
I have been trying to learn this library for 2 weeks. Thanks to good documentation and examples i have done basic requirements for my project easily. But as features gets complicated i have began to struggle.
So here is my problem. I'm using knockout.js for populating the table data. As you can guess column and row counts are dynamic. I'm also trying to achieve resizable columns with sticky headers. Updating row count do not cause any trouble but columns are really painful.

I need to recall something after column count is changed but using $(table).tablesorter() does nothing and sticky header remains unchanged and new columns are not sortable. $(table).trigger("updateall") makes the column sortable and resizable but all column widths goes back to default also my second row inside the header disappears.

This is too much text, I think example may explain it better: http://jsfiddle.net/LkqTU/23729/
+R = add row, -R = remove row, +C = add column -C = remove column
trig = $(table).trigger("updateall"), init =$(table).tablesorter()

Also there is more problems with this demo. Columns are not resizable before right clicking and columns could be shrink into 0 px width.

**Comment by Mottie** [comment]
Hi @seratkurtulus!

Thanks for that demo!

I think the main issue here is that the resizable widget does have a bug in which it always clears the storage when removed. I have been trying to fix this problem, but the ability to resize a column stops working after an "updateAll" is triggered... I'll have to wait till later this evening to do more troubleshooting as I have run out of time this afternoon.

As for updating, when a row is added or removed, you need to trigger an "update" method on the table so it rebuilds the internal cache. When a column is added or removed, you'll need to either trigger an "updateAll" method, or destroy tablesorter before re-initializing it. Calling tablesorter a second time `$('table').tablesorter();` doesn't do anything.

**Comment by seratkurtulus** [comment]
Hi @Mottie,

Thanks for the reply!

I think i gave up on resizable columns for now. It is nice to have for my project but not that much crucial. The problem with the triggering "updateall" is it removes the second row inside the sticky header. As a workaround i append those rows inside the table header and sticky table header again. 

But this time i have another problem: triggering "updateall" makes any row that is present inside the table not controllable by the knockout afterwards. They are not removed from table when rowCount is decremented but new row is added when rowCount is incremented.

I couldn't figure out how to solve this problem.

Here is the demo again showing what i mean: http://jsfiddle.net/LkqTU/23774/

**Comment by Mottie** [comment]
It appears that instead of using "updateAll", [destroying](http://mottie.github.io/tablesorter/docs/#destroy) tablesorter and reinitializing it works better ([demo](http://jsfiddle.net/Mottie/LkqTU/23781/)):

```js
// include false to prevent tablesorter class name from being removed
$('.tablesorter').trigger("destroy", false);
initializeTable();
```

I've never used knockout js before, so I'm not sure if it's working 100%... I can't seem to remove any of the original 15 rows.

**Comment by seratkurtulus** [comment]
Yes, I think you are right. I didn't notice that problem on my original project because i fade visible/invisible the rows that i want to filter or show. I mean, in that case there is no dynamically adding or removing rows and sorting doesn't make any problem.  Using same technique on columns may solve the problems regarding resizing issues but in my case it is not possible. Because i need to change orders of the columns also, which makes dynamically adding and removing necessity.

If "destroy" triggered in that scenario all of the visibility bindings are lost and all rows becomes visible but "updateAll" do not cause such problem.

Here is the demo with fading elements visible and invisible: http://jsfiddle.net/LkqTU/23783/

Thanks for the help.

**Comment by Mottie** [comment]
So,when you trigger an "updateAll" it calls the remove function of **all** installed widgets, not just the widgets listed in the [`widgets` option](http://mottie.github.io/tablesorter/docs/#widgets).

Because of the possibility of columns being removed or added, the filter widget removes the filter row and rebuilds it. I know you're not using the filter widget, but since the second row in the header has a "tablesorter-filter-row" class name, it is being removed. The filter widget also makes all rows visible upon removal.

So you have two choices:

1. Remove the "tablesorter-filter-row" class name, and instead of using `display:none` on the rows, add a class name, something like `hidden`, which has a defined `display: none` value.
2. Only load the widgets being used, like the stickyHeaders widget (zebra is part of the core) instead of using the `jquery.tablesorter.widgets.js` file. Or, you could create a [custom combined file](https://github.com/Mottie/tablesorter/wiki/Customize) that doesn't include the filter widget.

**Comment by Mottie** [comment]
Leaving this open to keep track of the issue with the resizable widget not working after an "updateAll" is triggered.
