### ISSUE TITLE
Output Widget (download) doesn't work with Safari

### ISSUE THREAD

**Issue by sozerberk** [Mottie/tablesorter#883]
Hi @Mottie , output widget's popup command works perfectly in Safari, Firefox and Chrome but Download button doesn't work in Safari (Version 8.0.5 (10600.5.17)). It doesn't even show the CSV, loading bar appears and disappears immediately without doing anything. Is there anything I should do?
Thanks!

**Comment by TheSin-** [comment]
sadly this is a known issue in safari and how it handles blobs.  There is no quick fix ATM for this, you can use my old gist I made from before output widget existed ;)  I've updated it to use the output widget data but you need php or something server to init the download with.  Hope it helps in the mean time.

https://gist.github.com/TheSin-/3303c23f033bd973bf34

**Comment by Mottie** [comment]
Hi @sozerberk!

I will try to add back the original code that did allow downloading in Safari... the main issue was that it required a [change to the `.htaccess` file](http://mottie.github.io/tablesorter/docs/example-widget-output.html#basic_setup) to work - at least according to @TheSin-, I blame him since I don't own any Apple hardware and Safari is no longer available for Windows.

**Comment by sozerberk** [comment]
Thanks a lot @TheSin- ! 
That worked like a charm.

**Comment by sozerberk** [comment]
Thank you for the explanation @Mottie!
I only tried the old script locally and it worked, but making a change to the `.htaccess` won't be a problem  when I transfer to the server in my case.
