### ISSUE TITLE
Support touch events

### ISSUE THREAD

**Issue by samacs** [Mottie/tablesorter#885]
I was trying to use this plugin with Ionic framework and realized that it does not support touch events. And I found it very simple to implement.

In file [js/jquery.tablesorter.js](https://github.com/Mottie/tablesorter/blob/master/js/jquery.tablesorter.js#L1344) around lines 1344 through 1350 just needed to add touchstart to the events bound to the headers to make it work:

```js
.unbind( ('mousedown mouseup click sort keyup touchstart '.split(' ').join(c.namespace + ' ')).replace(/\s+/g, ' ') )
.bind( 'mousedown mouseup click sort keyup touchstart '.split(' ').join(c.namespace + ' '), function(e, external) {
...
// only recognize left clicks
if ( ( ( e.which || e.button ) !== 1 && !/sort|keyup|click|touchstart/.test(type) ) ||
```

**Comment by Mottie** [comment]
Hi @samacs!

I thought `click` events were still fired on touch devices. Anyway, in anticipation of future support for [pointer events](https://github.com/jquery/PEP) I'll add three new options which will allow changing the sort triggering events:

* `pointerClick` - mouse click event (not really part of the pointer events). Additional custom events can be included in this option with event names separated by spaces (e.g. `'click makeItSo'`)
* `pointerDown` - pointer down (mouse or touch) event. This event only saves the current header cell being activated for a sort. 
* `pointerUp` - pointer up (mouse or touch) event. This event triggers a sort if the target of this event and the pointer down event match.

If you want to trigger a sort when the pointer down event fires, then set the `pointerClick` option to that event; Also set the `pointerDown` and `pointerUp` options to empty strings.

**Warning**: Do not set the `pointerDown` or `pointerUp` options to include multiple events of the same action. For example, if the `pointerDown` option is set to `"mousedown pointerdown"`, both events fire asynchronously and since tablesorter does not check for a time interval between events, both could potentially trigger a sort making the table column appear to not sort at all (if already sorted).

**Comment by KennedyIhe** [comment]
It will be nice if this enhancement can be worked on. The tablesorter plugin and scroll widget work great, but one problem is on iPad or other touch devices, touch and drag scroll is really slow and not user friendly. I had to apply a lot of custom fixes to make it scroll smoothly.
