### ISSUE TITLE
Sorting human readable large numbers in numeric order

### ISSUE THREAD

**Issue by nboughton** [Mottie/tablesorter#890]
I found that the "digit" metadata sorter doesn't work on large numbers that contain commas. My current fix was to add the following code to the jquery.tablesorter.js

```javascript
    ts.addParser({
        id: "humanReadableNumber",
        is: function (s) {
          return /^[\d,]+$/.test(s);
        }, format: function (s) {
          return s.replace(/,/g, ''); 
        }, type: "numeric"
    });  
```

Is there a better way to do this?

**Comment by Mottie** [comment]
Hi @nboughton!

The default digit parser should be replacing commas & decimals based on the [`usNumberFormat` option](http://mottie.github.io/tablesorter/docs/index.html#usnumberformat).

I'm not sure what is meant by "humanReadableNumber", since to me "one hundred and fifty" is a human readable number, and the above parser has a regular expression in the `is` function detecting numbers. The `format` function is very generic and would throw a javascript error if the `s` value was undefined (empty table).

There is already a named numbers parser ([parser-named-numbers.js](https://github.com/Mottie/tablesorter/blob/master/js/parsers/parser-named-numbers.js)) with a [demo](http://mottie.github.io/tablesorter/docs/example-parsers-named-numbers.html). It will need an update to ignore commas, so I'll push a fix for that shortly.

**Comment by nboughton** [comment]
Human readable may have been a poor label. Comma delimited is probably more apt.

i.e 1,234,567

What I found using the 'digit' parser was that all numbers after the first comma were ignored in the sort order.
