### ISSUE TITLE
Sorting a table with combobox using tablesorter plugin

### ISSUE THREAD

**Issue by budenk** [Mottie/tablesorter#909]
I have issue to make tablesorter plugin to sort combobox on Chrome and Firefox.
It is working fine on IE10.
Do you know what possibly causes it?

**Comment by Mottie** [comment]
Hi @budenk!

Can you please provide more information. What combo box? What code are you using? I demo would be really helpful here.

**Comment by budenk** [comment]
Here below is my code:
I am just using plain HTML.

Thanks.

<html>
<head>
<title></title>
<link rel="stylesheet" href="css/jq.css" type="text/css" media="print, projection, screen" />
<link rel="stylesheet" href="themes/blue/style.css" type="text/css" media="print, projection, screen" />



<script type="text/javascript" src="jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="jquery.tablesorter.js"></script>
<script type="text/javascript" language="javascript">
	
						$.tablesorter.addParser({
				    id: "select",
				    is: function () {
				        return false;
				    },
				    format: function (s, table, cell) {
				        return $(cell).find('select').val() || s;
				    },
				    type: "text"
				});
				
				// update select in the tablesorter cache when the change event fires.
				// This method only works with jQuery 1.7+
				// you can change it to use delegate (v1.4.3+) or live (v1.3+) as desired
				// if this code interferes somehow, target the specific table $('#mytable'),
				// instead of $('table')
				$(window).load(function () {
				    // this flag prevents the update event from being spammed
				    var alreadyUpdating = false;
				    $("#tablesorter-demo").find('tbody').on('change', 'select', function (e) {
				        if (!alreadyUpdating) {
				            alreadyUpdating = true;
				            $(this).trigger('update');
				            setTimeout(function () {
				                alreadyUpdating = false;
				            }, 10);
				        }
				    });
				});
				
				$("#tablesorter-demo").tablesorter({
				    headers: {
				        1: {
				            sorter: 'select'
				        }
				    }
			});


	$(function() {		
		$("#tablesorter-demo").tablesorter({sortList:[[0,0]], widgets: ['zebra']});
		

	});	

</script>
</head>
<body topmargin="0" leftmargin="0" marginheight="0" marginwidth="0" bgcolor="#ffffff" link="#0b0b5a" vlink="#0b0b5a" alink="#800000">



	<form method='post' id='theForm' name='theForm'>

	
<div align="center">	
<table border='1' cellpadding='2' cellspacing='1' align='center' id='tablesorter-demo' class='tablesorter' width='800'><thead>
<th width='250' bgcolor='#4E7DD1'><font size='2' face='arial' color='white'>Employee Name</font></th>
<th width='300' bgcolor='#4E7DD1'><font size='2' face='arial' color='white'>Number</font></th>
</thead>
<tbody>
<tr><td bgcolor='#FAF7E2'><font size='2' face='arial' color='black'>John Smith&nbsp;</font></td>
<td bgcolor='#FAF7E2'>
<select name='cboSuper0' style='width=200px'><option value=''></option>
					<option>1</option>
					<option>2</option>					
					<option>3</option>					
				</select></td>
</tr>
<tr><td bgcolor='#FAF7E2'><font size='2' face='arial' color='black'>Brian Dunn&nbsp;</font></td>
<td bgcolor='#FAF7E2'>
<select name='cboSuper1' style='width=200px'><option value=''></option>
					<option>1</option>
					<option>2</option>					
					<option>3</option>						
				</select></td></tr>				
		<tr><td bgcolor='#FAF7E2'><font size='2' face='arial' color='black'>Don King&nbsp;</font></td><td bgcolor='#FAF7E2'><select name='cboSuper2' style='width=200px'><option value=''></option>
			<option>1</option>
					<option>2</option>					
					<option>3</option>		
			
				</select></td></tr>
<tr><td bgcolor='#FAF7E2'><font size='2' face='arial' color='black'>Andy Phillips&nbsp;</font></td><td bgcolor='#FAF7E2'><select name='cboSuper3' style='width=200px'><option value=''></option>
			<option>1</option>
					<option>2</option>					
					<option>3</option>		
			
				</select></td></tr>

		</tbody></table>
</div>
	
</form>

</body>
</html>

**Comment by Mottie** [comment]
Oh! I totally misunderstood LOL

What is needed is the [`parser-input-select.js` file](https://github.com/Mottie/tablesorter/blob/master/js/parsers/parser-input-select.js) to use the select parser; *make sure to use the file from the master branch*. It includes code to automatically update the cache when the user changes the select (see the [group widget demo](http://mottie.github.io/tablesorter/docs/example-widget-grouping.html))

Then all you need to do is add a "sorter-select" class name to the header cell ([demo](http://jsfiddle.net/Mottie/856bzzeL/234/))

```html
<th class="sorter-select" width='300' bgcolor='#4E7DD1'><font size='2' face='arial' color='white'>Number</font></th>
```

I would recommend not using `width` and `bgcolor` attributes, and the `<font>` tag. All of this styling can be done using css.

Also, because IE has issues when using an option in a select without a set `value` attribute, I would recommend including that attribute as well.

**Comment by budenk** [comment]
Rob,

I did the change as you suggested. It is working fine Chrome and FireFox, but It does not work on IE10 if I use TableSorter version v2.21.5. 
If I use TableSorter Version 2.0.5b, it is working on IE10, but I does not work on Chrome and Firefox.
How do you make it work on all browsers using the same version of TableSorter?

Thanks!

**Comment by Mottie** [comment]
Do you see any errors in the console in IE10?

I would recommend running the HTML through a [validator](https://validator.w3.org/) and fixing any suggestions.

**Comment by budenk** [comment]
I found out it was the document mode. I changed to use standard document mode from the meta tag and it fixed the issue. Thanks!

**Comment by budenk** [comment]
The table sorter becomes really slow to load and sort if we have more than 300 drop down list. 
Is there anyway to speed up?

**Comment by Mottie** [comment]
Can you please provide a demo... all the values of the dropdowns are stored in a cache so there shouldn't be any change in sort speed. When a dropdown is changed, the "updateCell" method is used to update the cache, so that shouldn't cause any significant delays.

So maybe this is only a load issue? How is the table populated? Is it updated by ajax, or is it already formed on the page? What code is executed before & after tablesorter? What widgets are being used? Does the table have an initial sort? How many licks does it take to get to the tootsie roll center of a tootsie pop?

Almost all of these questions can be covered by providing a demo of the problem.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.
