### ISSUE TITLE
Since last update, header inputs no longer accessible...

### ISSUE THREAD

**Issue by Francks11** [Mottie/tablesorter#911]
Hello @Mottie,

since last update, header inputs are no longer accessible.

You can see this here : http://jsfiddle.net/Francks11/oqfq47fc/1/

Why?

Thanks

**Comment by Mottie** [comment]
Hi @Francks11!

It's because of [this line](https://github.com/Mottie/tablesorter/blob/master/js/jquery.tablesorter.js#L1401-L1402):

```js
// needed or jQuery v1.2.6 throws an error
e.preventDefault();
```

I'm not sure why, but if I comment out that prevent default, jQuery v1.2.6 will throw an "Uncaught TypeError: handler.apply is not a function".

Maybe it's time to drop support for 1.2.6?

**Comment by Francks11** [comment]
Hi @Mottie,

I use currently version v1.7.2 of jQuery...

Thanks

**Comment by Mottie** [comment]
Yes, but tablesorter supports jQuery v1.2.6, so I need to find a work around or remove support for that really old version.

**Comment by Francks11** [comment]
jQuery 1.2.6 is out May 24, 2008.

Indeed, it is time to drop support if that is not possible otherwise. :-p

**Comment by Mottie** [comment]
Does that table even sort?... if I right-click in the input, I can get focus to it, and yes, I know that isn't ideal.

**Comment by Francks11** [comment]
For this case, I do not use sorting because the data must appear in a specific order.

But I use scroller widget for fixed header and fixed columns...

Its not very practical with the right click :-)

**Comment by Francks11** [comment]
Why have you the need to add this code e.preventDefault(); from this version?

**Comment by Mottie** [comment]
Umm, because there was an error in jQuery v1.2.6?

It should work now... the update is in the master branch.

**Comment by Mottie** [comment]
[Here is your demo](http://jsfiddle.net/oqfq47fc/21/) using the core from the master branch.

**Comment by Francks11** [comment]
okay thanks for your reactivity. :-)

**Comment by Francks11** [comment]
Other problem is that it is no longer possible to select the text in the field with mouse... for example, to replace text...

**Comment by Francks11** [comment]
I encounter a other issue with header input fields...

It is no longer possible to select the text in the field with mouse with Internet Explorer, for example, to replace text.

**Comment by Mottie** [comment]
Set the [`cancelSelection` option](http://mottie.github.io/tablesorter/docs/#cancelselection) to `false` ([demo](http://jsfiddle.net/oqfq47fc/23/)).

**Comment by Francks11** [comment]
Thanks :-), a lot of options unknow.

**Comment by Francks11** [comment]
Hi @Mottie, @TheSin- ,

I suggest you to improve cancelSelection, do not apply on input in header columns.

Use case :

I don't want that the header text can be select, but I would like that the text can be select on input.

Thanks. :-)

**Comment by Mottie** [comment]
The cancel selection is applied to the header cell, not the inputs.

Since you have a extra rows in the header that are not used for sorting, you can use the same method the filter widget uses by adding "tablesorter-ignoreRow" (set by [`cssIgnoreRow`](http://mottie.github.io/tablesorter/docs/#cssignorerow) to rows that you don't want to be included with `config.$headers` ([demo](http://jsfiddle.net/oqfq47fc/44/)).

```html
<tr class="tablesorter-ignoreRow">
    ...
</tr>
```

I'll update the docs to emphasize this fact.

**Comment by Francks11** [comment]
Thanks :-)
