### ISSUE TITLE
Horizontal scroll resets when column sorted.

### ISSUE THREAD

**Issue by SPlatten** [Mottie/tablesorter#932]
Not a big deal, but:

Scroll the table horizontally so that some columns are scrolled out of view, click on a header to sort the column.  When sorting data the table view is reset so you have to scroll back to where you were.

Ideally it would be useful if clicking on a column header doesn't appear the horizontal scroll.

**Comment by Francks11** [comment]
Can you provide a demo please?

**Comment by SPlatten** [comment]
http://jsfiddle.net/1a5yu8yq/41/

This shows it quite clearly, scroll right on the horizontal scrollbar, click the header sort order, the table is refresh with the scroll reset to the left.

**Comment by Francks11** [comment]
Okay I see. Its also appears when resizing.

I have the same issue : https://github.com/Mottie/tablesorter/issues/926

 but with vertical scrollbar, and it is not resolved for now.

I have look to the code, but I have not found yet the way to solve this bug.

**Comment by TheSin-** [comment]
this is due to the tables rebuilding to fix this we might need to save the scroll locations and reset them after the refresh, I'm trying thinking about this a little.

it's not a bug in setupFixed, it's just how it's done since fixed cols are removed to get proper sizing then rebuilt, in doing so it resets the scroll.
