### ISSUE TITLE
Automated Code Formatting Check

### ISSUE THREAD

**Issue by Herst** [Mottie/tablesorter#950]
Here a JSCS formatting file helping with that: https://gist.github.com/Herst/39263a478046a48f1860

I basically just updated my style file to match your code style by comparing it with tablesorter.combined.js and an arbitary selection of other widgets.

**Comment by Herst** [comment]
Of course there are some settings I didn't set at all.

**Comment by Mottie** [comment]
Thanks! I added a link to the [contributing.md](https://github.com/Mottie/tablesorter/blob/master/CONTRIBUTING.md#contributing-code)!

**Comment by Mottie** [comment]
Added to `grunt test` in https://github.com/Mottie/tablesorter/commit/75de112ef6f3d1c0010eeaef40b28340716ffa13.

**Comment by Mottie** [comment]
Oh, in response to your question, I did have to modify the `.jscrc` file:

* Removed `"disallowQuotedKeysInObjects": "allButReserved"` - I like to add single quotes around the object keys, but I guess I'm not consistent. Here is an example from the scroller widget

	```js
	getBarWidth : function() {
		var $div = $( '<div>' ).css({
			'position' : 'absolute',
			'top' : '-9999px',
			'left' : 0,
			'width' : '100px',
			'height' : '100px',
			'overflow' : 'scroll',
			'visibility' : 'hidden'
		}).appendTo( 'body' ),
		div = $div[0],
		barWidth = div.offsetWidth - div.clientWidth;
		$div.remove();
		return barWidth;
	},
	```

	I guess it wouldn't hurt to add that setting back and clean up the code some more.

* Removed `"disallowSpacesInsideParentheses": true` - in this case, in the newer code I'm writing, I've started adding space inside of parentheses because I guess I'm getting old and it makes it more readable for me. Again, not consistent because I haven't gone back and reformatted all the old code.

* Removed `"requirePaddingNewLinesAfterBlocks"` completely because it was forcing a new line after every `if { }` block... I wasn't sure how to override it.

* Removed `"validateLineBreaks": "LF"` because it's already being normalized by the `text=auto` in the `.gitattributes` file.
