### ISSUE TITLE
Filters not working on load

### ISSUE THREAD

**Issue by VictorT83** [Mottie/tablesorter#952]
The filters appear to be set during initialization, however it does not appear that the filter is actually being applied despite the third parameter being set to true.

If I try setting the filter manually after the table has fully loaded it seems to work, or if I set a timeout of 100ms or more, it seems to work, but it does not not appear to like a default filter.

Here is a fiddle:
http://jsfiddle.net/abkNM/6148/

**Comment by Mottie** [comment]
Hi @VictorT83!

There's a lot of stuff going on during initialization. Instead of trying to set the filters in teh initialization callback, use the "data-value" attribute (set by the [`filter_defaultAttrib` option](http://mottie.github.io/tablesorter/docs/#widget-filter-defaultattrib) with the initial filter value ([demo](http://jsfiddle.net/abkNM/6150/)):

```html
<th data-value="abc">AlphaNumeric</th>
```

Note: if the [`filter_saveFilters` option](http://mottie.github.io/tablesorter/docs/#widget-filter-savefilters) is `true`, then any saved filters will override the "data-value" setting on initialization.

**Comment by VictorT83** [comment]
Perfect, Thank you.
