### ISSUE TITLE
Strange behaviour with Chrome

### ISSUE THREAD

**Issue by ciadch** [Mottie/tablesorter#956]
Hello,

When I display my web page with Chrome, my table (whatever the size) is firstly displayed as simple html table before tablesorter is applied. It's really strange, when I try the sampe thing wit IE or Firefox, no problem, my table is fully displayed with tablesorter applied. I miss something or is there an option that i forgot ? In my code, I user the boostrap theme.

This behavior appears only when my scripts are included after html code (link example below)

Thanks for your reply,

Cheers,
ciadch

**Comment by ciadch** [comment]
After a few search, it seems that is the filter widget who thake time to be displayed

**Comment by ciadch** [comment]
Exemple :
![beahaviour](https://cloud.githubusercontent.com/assets/12936546/8473264/75b7ae56-20a8-11e5-87ca-31a0acdd48c6.png)

**Comment by Mottie** [comment]
Hi @ciadch!

What you are seeing is called the [flash of unstyled content](https://en.wikipedia.org/wiki/Flash_of_unstyled_content), FOUC for short. Although, it's not due to the stylesheet being loaded after the DOM is ready - it is due to the table not having any style applied initially.

In order to prevent this from happening, add the class names that will be applied to the table element after it becomes initialized by tablesorter:

```html
<table class="tablesorter-bootstrap table table-bordered table-striped">
...
</table>
```

* `table-bootstrap` is the class name used by tablesorter for the Bootstrap theme.
* `table table-bordered table-striped` are class names used by Bootstrap.

To get a better idea of this issue, check out [this demo](http://jsfiddle.net/Mottie/njj5b5vc/33/) where I use a `setTimeout` to delay tablesorter initialization.

**Comment by ciadch** [comment]
Awesome ! Thanks for the tip ! I make a workaround for hiding my table until whole tablesorter is initialize. Seem work correctly !

**Comment by Mottie** [comment]
Please be aware that even though Bootstrap css provides striping of the table rows using css, that if there is an initial filter and the table is hidden the striping may not appear correct - try filtering the table [in this demo](http://mottie.github.io/tablesorter/docs/example-widget-bootstrap-theme.html) with the zebra widget disabled.

This problem is due to the zebra widget only applying class names to visible rows. So if the entire table is hidden, the zebra widget won't apply any class names to the rows to fix the striping.

I hope that makes sense.

**Comment by ciadch** [comment]
Thanks for this advice. In my case, I don't have any initial filter so everything works good with hidden table at the beginning. So no problems with zebra widget too.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
