### ISSUE TITLE
Need to sort a table and get the url and share with others which shows the sorted result

### ISSUE THREAD

**Issue by divyaalex** [Mottie/tablesorter#962]
I have a table which I am sorting on multiple columns (using shift+click) using  jquery.tablesorter.combined.js and using saveSort widget 
to save the sort.

is there any way i can sort this in server side and get the url so that I can copy & paste the url and share this result with others via URL ?
Loading this URL should give me the sorted table as it is.

Please let me know 

Thanks in advance 
divya

**Comment by Mottie** [comment]
Hi @divyaalex!

I answered your question on [Stackoverflow](http://stackoverflow.com/q/31377639/145346) - I forgot you opened an issue as well.

Basically my solution was to add a new ["sort2Hash" widget](https://github.com/Mottie/tablesorter/blob/master/js/widgets/widget-sort2Hash.js) which saves the current sort to the browser location hash. It does not change the browser history.

You can see it working in [this demo](http://jsfiddle.net/Mottie/856bzzeL/546/), except JSFiddle doesn't restore the embedded iframe hash when you re-run the demo, so you can't really see it working. I did create [a demo in the documentation](http://mottie.github.io/tablesorter/docs/example-widget-sort-to-hash.html), but it is only currently available in the master branch. I'll push it to the gh-pages branch in the next version update, **so that link won't work until then**.

**Comment by divyaalex** [comment]
Hi,

Thank you for this awesome widget its working for me well.

Some issue I see here is when I shift click and select the columns to sort  I get a link  like this 
http://localhost/test/run.php?pgm=20150714#&resultTable=0,0,1,0,2,0,3,0,4,0

now when I delete this string (#&resultTable=0,0,1,0,2,0,3,0,4,0) from url and reload the page the same string will get appended to the url,and instead of loading a fresh page the old page is again loading  where I have my sorted result .
Is it possible to load the page with the given url in case of new page load?
.Also I see that when browser cache is cleared the new page is loading with the given URL with out appending the result table string.



 Also for my code table header

printf("<a href=javascript:void(0)>%s</a>", $colnames[$column]);

When I click on the table header, Mozilla is opening a new blank window.
Where as in google chrome this behaviour is not observed.


Also one more thing I noticed with both browsers(chrome nd firefox) is that 
I copied the URL http://localhost/test/run.php?pgm=20150714#=&resultTable=0,0,1,0,2,0
 and pasted in firefox ,where I already have 1 tab opened with 
URL http://localhost/test/run.php?pgm=20150714#=&resultTable=0,0,1,0,3,1 ,the above URL I pasted in new tab also changed to the existing URL (http://localhost/test/run.php?pgm=20150714#=&resultTable=0,0,1,0,3,1)

Is it like in one browser session we can open only one test result?Opening in new tabs is giving 
incorrect result.

Please advice how to proceed on this.

Thanks in Advance!
Divya

**Comment by Mottie** [comment]
I think the problem with the same string reappearing is due to the `saveSort` widget. Remove that and the problem should go away.

How are you using `href=javascript:void(0)` in the header?

The other browser tab problems you mention sounds like it's a Firefox option that is set to always open a new tab.

**Comment by divyaalex** [comment]
Yes ,I removed saveSort and it is working as expected.Thank You!

**Comment by divyaalex** [comment]
Right now the browser URL is getting updated with table column indexes (&resultTable=0,0,1,0,3,1).
Is there a way I can replace these indexes with my column names.
(0,0 Hostname, 0,3 Testname ) or some abbreviations "(HNAM,TNAME etc..) for the columns ?

**Comment by Mottie** [comment]
It would be possible, but it would require changing the widget code & encoding the URL, because it appears that there will be spaces. Also, the first number is the column index, the second is the sort direction, which can also be replaced with text:

    &resultTable=Last%20Name,descending,First%20Name,ascending,Address,ascending

Does the column change position? Why make it more complicated? The user won't be able to easily read the URL with encoded spaces.

**Comment by divyaalex** [comment]
The column may change position,because I have option to add and remove columns in the table.

This will be good to have because,whoever viewing the URL can see
 on which columns the sort has been performed and in which order .

**Comment by Mottie** [comment]
Ok. I won't be able to work on this change for a few days...

**Comment by justinmeats** [comment]
Love this widget, thank you.  I needed this functionality and was glad I found this, especially since it is still so new.

How hard would it be to get this widget to work with the saveSort widget?  I would like to use both widgets.  If the sort is present in the hash, use that, otherwise use the sort saved in storage.

**Comment by Mottie** [comment]
Hi @justinmeats!

I'll look into that request as well.

**Comment by Mottie** [comment]
* Add `sort2Hash_useHeaderText` - use column header text or zero-based index
* Add `sort2Hash_processHeaderText` - extra column header text processing
* Add `sort2Hash_directionText` - sort direction text array
* Add `sort2Hash_overrideSaveSort` - override saveSort stored sort if true

**Comment by Mottie** [comment]
[Updated demo](http://jsfiddle.net/Mottie/856bzzeL/561/) - after some bug fixes.

**Comment by divyaalex** [comment]
Thanks a lot for this quick code change ...and Best wishes.....:)

**Comment by justinmeats** [comment]
Thanks, or should I thank the OCD?  (It really should be called CDO with the letters in the proper order)

**Comment by Mottie** [comment]
LOL exactly!

**Comment by divyaalex** [comment]
When I added the new widgets (/*! Widget: sort2Hash - updated 7/21/2015 (v2.22.4) */) I am getting error 

Uncaught ReferenceError: $table is not defined  jquery.tablesorter.combined.js:1710 Uncaught ReferenceError: $table is not defined

ts.hasWidget = function(table, name){
				$table = $(table); //error here
				return $table.length && $table[0].config && $table[0].config.widgetInit[name] || false;
			};

Also when the page first loads the header is not displaying any style,I have to click on the header for it to display the asc/dsc arrows.
Will you please take a look..

My scripts includes 
   <script type="text/javascript" src="extlib/jquery.min.js"></script>
 <script type="text/javascript" src="extlib/jquery.tablesorter.combined.js"></script>
   <script type="text/javascript" src="extlib/widget-sort2Hash.js"></script>


Also one more issue I have is I have two tables in my page One table has 

$altrow=TRUE;
<tr class="%s">', $altRow ? 'altrow' : '' );
        $altRow = !$altRow;

in CSS:

#content tbody tr.altrow td {
  background-color: #444444;
}

In the second table I have tablesorter,so for this when I apply widget 'Zebra',it does not affect.The table background is blank.
I applied the same for this second table (tr class=altrow) too then it works .
how can I fix this?I want to use zebra widget in my second table  too...

I see that for table sorter the class name comes even,odd by default.How can i change to altrow?

**Comment by Mottie** [comment]
Please get the latest update from the master branch. I pushed a fix for the `hasWidget` function yesterday in https://github.com/Mottie/tablesorter/commit/a0d29c99f4c83e80ae35237935051765fad64da7. After you update, everything should work as expected.

**Comment by divyaalex** [comment]
I think now it is not preserving the sort...it fixed the header issue...
when i navigate and come back ,or copy paste url its loading a fresh page...
Am i missing something ..not sure...

**Comment by divyaalex** [comment]
i feel its some problem with spaces in header when i sort with product and size its preserving,but Host Name,Test Name (which has spaces in header field create issue ?)

**Comment by Mottie** [comment]
If you copied the code from the last demo I shared, I included some code in the `sort2Hash_processHeaderText` callback:

```js
sort2Hash_processHeaderText: function( text, config, columnIndex ) {
    // remove all non-alphanumeric characters (including spaces)
    return text.replace(/[^a-z0-9]/gi, '');
},
```

This code removes the spaces (`%20`), and any odd characters like `£` (which becomes `%C2%A3`) in the header text. I only added it to make the url more readable.

**Comment by divyaalex** [comment]
yes...I removed that....working fine...Thanks...
