### ISSUE TITLE
columnSelector: multiple tables & container name difficulty

### ISSUE THREAD

**Issue by aeryn21** [Mottie/tablesorter#974]
I have two tables, maximum, on a page that use the columnSelector widget.  I am having issues getting both, and sometimes any, to work.

First run through, I didn't change the container names to be unique, so the column selection options were both showing up in the first #columnSelector box.  Ok, make them unique.  I used the code

```
columnSelector_container : $('#columnSelector<?php echo $rockets_motor_size; ?>'),
```
and 
```
<div id="columnSelector<?php echo $rockets_motor_size; ?>" class="columnSelector"> </div>
```
to add uniqueness to the selector.  

When pulled up the source code, they look like 
```

		  $(document).ready(function() { 
		  
			/*** custom css only button popup ***/
			$("#tablesorterMotorchart18").tablesorter({
				
			  widgets: ['zebra', 'columnSelector', 'filter'],			  
			  textExtraction: function(node) 
			  {
				return node.getAttribute('sortvalue') || node.innerHTML;
			  },
			  
			  headers: { 
				//'.products_id': {filter: false, sortInitialOrder: "desc" },
				//'.products_buy': {filter: false, sorter: false}
				7: {sorter: false, filter: false} 
			  },
			  widgetOptions : {
										
				columnSelector_container : $('#columnSelector18'),
				// column status, true = display, false = hide
				// disable = do not display on list
			   
				// remember selected columns (requires $.tablesorter.storage)
				columnSelector_saveColumns: true,
		  
				// container layout
				columnSelector_layout : '<label><input type="checkbox">{name}</label>',
				// data attribute containing column name to use in the selector container
				columnSelector_name  : 'data-selector-name',
		  
			       //..........
			  }
			});
		  });  // end document.ready 
```
```
<div class="columnSelectorWrapper">
      <input id="colSelect18" type="checkbox" class="hidden">
      <label class="columnSelectorButton" for="colSelect18">Show Columns</label>
      <div id="columnSelector18" class="columnSelector">
            <label><input type="checkbox" data-column="auto" class="checked">Auto: </label> 
             <!-- this div is where the column selector is added --> 
            <label class="disabled"><input type="checkbox" data-column="2" class="checked" disabled="">Color</label>
            <label class="disabled"><input type="checkbox" data-column="3" class="checked" disabled="">Comment</label>
            <label class="disabled"><input type="checkbox" data-column="5" class="checked" disabled="">Delay*</label>
            <label class="disabled"><input type="checkbox" data-column="7" class="checked" disabled="">Buy Now!</label>
        </div>
            <div class="screenDataShown"><strong>Not All Data Shown.</strong> Expand your browser or select options above.</div>
</div>
```

Except it still didn't work, even when each code was unique.  So, I commented out the 2nd table temporarily.  Still not working with my variable selector on a single table.  So, I removed the php and used IDs of "columnSelect" instead of "columnSelector" and still nothing.  Changed it back so that they are "columnSelector" and bam, it works beautifully as it should.  So, now I'm thoroughly confused.  

The information is THERE, but when I click the button, nothing happens to reveal the information.  Is it a css issue?  JS issue?  I get errors or warnings for neither in my console or log.  I have tested in Safari, Chrome, FF and Opera.

Development Site Example Page, with it set up with 2 tables using the php variable:  http://beta.apogeerockets.com/Rocket_Kits/Skill_Level_1_Kits/Apprentice_Rocket_Kit

**Comment by Mottie** [comment]
Hi @aeryn21!

I think the issue might be that the css needs to include the unique IDs as well.

```css
#colSelect18:checked + label {
    background: #5797d7;
    border-color: #555;
}
#colSelect18:checked ~ #columnSelector18 {
    display: block;
}
```

I set up that demo to use only css for the popup, you might be better off using jQuery to add/remove a class name to make the popup visible.

Also, you don't need to include that `textExtraction` function because you can change the [`textAttribute` option](http://mottie.github.io/tablesorter/docs/#textattribute) (default is `"data-text"`) to match your extra data:

```js
$(function() {
	$("#tablesorterMotorchart18").tablesorter({
		widgets: ['zebra', 'columnSelector', 'filter'],
		textAttribute: 'sortvalue',
		headers: {
			//'.products_id': {filter: false, sortInitialOrder: "desc" },
			//'.products_buy': {filter: false, sorter: false}
			7: {sorter: false, filter: false}
		},
		widgetOptions : {
			columnSelector_container : $('#columnSelector18')
		}
	});
}); // end document.ready
```

I removed the options that were already set as their default value

**Comment by Mottie** [comment]
Oh, and sorry, I have some more unsolicited advice...

This is the most important one to fix:
* I noticed multiple (at least 3) copies of jQuery being loaded on the page. Just load it once, at the top.

These are suggestions, so do what you want with them:
* Combine all the extra css on the page and move it into an external file. Better yet, take all the css on your page and compress it into one file.
* Combine all the extra javascript on the page and move it into an external file. Again, it would be even better to combine it all and compress it into one file.
* Check the HTML - there are [numerous validators out there](http://webdesign.about.com/od/htmlvalidators/tp/best_html_validators.htm). I only mention this because I saw a few extra tags in the code.

**Comment by aeryn21** [comment]
Thanks!  I'll implement those changes and report back.  :)

**Comment by aeryn21** [comment]
CSS still wasn't working.  :/  I switched to your Bootstrap method, attaching to IDs instead of the class, and both are working individually now.    Few more tweaks and we'll be set.   And I have no idea why 3 instances of jquery were in there.  Suppose that's what I get for using other folks' modules and not fully reading the code before integrating.

**Comment by Mottie** [comment]
So, it sounds like you're all good now. I'll go ahead and close this issue. If you do continue to have problems, feel free to continue the discussion in this thread.
