### ISSUE TITLE
pasting from Excel...:(

### ISSUE THREAD

**Issue by Stephen-Hazel** [Mottie/tablesorter#994]
when ya click on a cell in excel and copy to the clipboard it puts a buncha crappy html into the clipboard like...

```html
<tr height="20">
  <td style="height:15.0pt;width:48pt" height="20" width="64">a</td>
</tr>
```

(Actually, probably even a table around ^^THAT junk) and when you paste that crap into ole tablesorter content-editable, it totally corrupts the html that tablesorter is dealin' with.
Can you think of some way to keep this from happening?  Some sort of defense against excel?

What's weird is that wordpad and notepad seem to paste just fine, (only the cell's content is pasted) but upon tabbing out of the tablesorter field, I have some console.logs that show crazy html in the field...:(

Any chance ya know what the deal is with this?

**Comment by Mottie** [comment]
Hi @Stephen-Hazel!

You have a few options:

* Use the [`editable_complete`](http://mottie.github.io/tablesorter/docs/example-widget-editable.html#editable-edit-complete) triggered event (default is `editComplete`) to modify the cell contents after pasting... but it's probably not the most efficient method. Since you would need to update the cache a second time.
* Use the [`editable_validate`](http://mottie.github.io/tablesorter/docs/example-widget-editable.html#editable-validate) callback function and have it return the modified text:

    ```js
    $('table').tablesorter({
      widgets : ['editable'],
      widgetOptions : {
        // global validate function
        editable_validate : function(txt, orig, columnIndex, $element){
          return $element.text();
        }
      }
    });
    ```

* Lastly, you could use the right click "Paste as plain text" method

    ![test](https://cloud.githubusercontent.com/assets/136959/9284191/3ea071fa-429f-11e5-9b1e-1cf0e373c9ea.gif)

Or, maybe you were asking me to add something internally to prevent pasting in HTML? That shouldn't be a problem, but I would likely add an option to use or not use that functionality.

**Comment by Stephen-Hazel** [comment]
Hiya.  I was just looking for some workaround so Excel doesn't murder my table and put crap into the back end.  So I think the editable_validate thing will do the trick.  The only thing that should be in a cell is a string (for me).  So all I gotta do is use your option 2 above, eh?  that'll play nice with editable_wrapConent of '<div>' hopefully.  I'll give it a shot.  OK!  That works like a charm.

Thanks yet again for helpin' out a guy who is not Mr. Javascript/JQuery 

I guess I let you close this thing, If I recall.

**Comment by Stephen-Hazel** [comment]
Oh and that paste as plain text must be browser dependent - didn't see it in Firefox fyi

**Comment by Mottie** [comment]
Hmm, that is odd... I guess paste as plain text is only in Chrome.

I'll leave this open. I'm still considering if an option to strip out HTML would be easier.

**Comment by terwarf** [comment]
Hi @Mottie, hi @Stephen-Hazel,

I have a simple parser for copying values from spreadsheets - tested only with libre office, since I don't use MS-Office. Maybe it's of any use for you.

http://jsfiddle.net/terwarf/v4zar9d8/

**Comment by Mottie** [comment]
Hi @terwarf!

Thanks, I'll try it out with MS-Office!

**Comment by Mottie** [comment]
Hey @Stephen-Hazel!

Sorry for taking so long. I don't know why I didn't think of this method sooner... I just added a listener for the "paste" event and converted whatever content that was pasted into plain text.

Please test it out for me. I hope this doesn't cause any conflicts.

**Comment by Mottie** [comment]
Version 2.25.5 is now available!
